### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/ui#1040]
Hi,
in the dashbord of the new web ui there are two missing texts:
- 
![image](https://github.com/invoiceninja/ui/assets/28981528/6c078cea-cc65-4811-9e68-5f9e3ff6479a)
- And in the dashboard graph settings
![image](https://github.com/invoiceninja/ui/assets/28981528/9dec226b-c55f-42b0-ab49-93b153ff31a0)

**Comment by turbo124** [comment]
@LarsK1 

We are just waiting on the translations to merge, this is correct in one of the current PRs
