### ISSUE TITLE
Can't select Product in new Invoice

### ISSUE THREAD

**Issue by greenwaym** [invoiceninja/ui#1047]
Steps to reproduce: 
- Create new invoice
- Select customer
- Add product
- Try to change the product

I can't select a different product, after adding a product to the invoice. This morning, everything was still working fine, I guess the latest update created the problem. 

Using hosted InvoiceNinja with the React Web UI
![Screenshot 2023-08-15 191226](https://github.com/invoiceninja/ui/assets/103878409/a1701a36-0892-4040-a366-93db7f174a11)

**Comment by turbo124** [comment]
This should be resolved in the latest release.
