### ISSUE TITLE
CSS failures and creation of Reminders and Dunning out from Dropdown

### ISSUE THREAD

**Issue by pthoelken** [invoiceninja/ui#1076]
Current Version: 5.7.5 in Self Hosted Environment

**Informations**
**Point 1:** Before few versions I can do dupe a invoice to a reminder / dunning out from the invoice table. Now it's gone and more complicated. So in my UI I can't find it anymore (for both UI; Flutter and React). Is there any chance to get it back? It will be much more comforble and smarter to create reminders.

**Point 2:** Check the Dropdown Menu CSS errors form the pictures. :-)  

Point 3: Maybe a side menu points with "Reminders / Dunnings" which I send to customers? And also a Side menu entry in the customer portal.

Point 4: Show Reminders and Dunnings correctly in the Invoice History. 

**Screenshots**
![image](https://github.com/invoiceninja/invoiceninja/assets/12643853/43d7db31-d881-4e6d-ab10-ae9ce1eda421)

**Comment by turbo124** [comment]
We haven't changed of the cloning functionality in the app. Which document type exactly are you trying to clone into?

For the CSS issue, we'll take a look, ping @beganovich

**Comment by pthoelken** [comment]
I've tried to clone from a normal invoice (which is overdue) to a reminder / dunning which I can send to a customer. The picture above comes from the menu tab "Invoices". 

So I can create a "Reminder" by clicking no "Invoice send" from the dropdown menu and then select "First Reminder". But IMHO this is not the right way to send an official and important document like an reminder or dunning to a customer. This should be handled a little more delicately for IMHO.

**Comment by turbo124** [comment]
@pthoelken so this is a feature request rather than a bug? You said the option was missing and existed previously?

**Comment by pthoelken** [comment]
I mean and might remember that these function exists in the past. 

If it’s definitely not, you can register this as feature request. 😊

**Comment by turbo124** [comment]
@pthoelken trying to figure out if any action needs to be done here, From the Send Email screen, you can now select the template and update any content prior to sending... can you advise if this issue can be closed now?
