### ISSUE TITLE
Templates and Reminders: Should not allow an empty value in the field "Days" for reminders

### ISSUE THREAD

**Issue by vincentdh** [invoiceninja/ui#1097]
## Issue description
When you configure a reminder using the ReactUI, the form allows you to delete what's in the "Days" field and save the parameters. On the server side, there is no validation either and an empty string is saved in the database. However, the flutter app expect to receive an integer and so it throws a deserialization error which prevent you from login.

## Expected behavior
The "Days" field should either be set as required or, like in the flutter app, be set to 0 if it's empty.

**Comment by vincentdh** [comment]
Oh, by the way, the react ui looks much cleaner than the flutter app! You did a great job guys!

**Comment by turbo124** [comment]
Thanks for reporting.
