### ISSUE TITLE
Text boxes public and private remarks hidden

### ISSUE THREAD

**Issue by LaurensVanAcker** [invoiceninja/ui#1119]
The text boxes for public and private remarks are not visible anymore in the React interface:
![Screenshot 2023-09-17 122022](https://github.com/invoiceninja/ui/assets/4385000/ea732a34-3882-4af6-8c06-1d0b77057bbb)

**Comment by turbo124** [comment]
Are you on the latest version?

**Comment by LaurensVanAcker** [comment]
Version **v5.7.13** of the backend and **15.09.2023.1** of the React code.
