### ISSUE TITLE
Latest release is missing react build zip causing docker container builds to fail at the fetch step

### ISSUE THREAD

**Issue by anojht** [invoiceninja/ui#1128]
To keep this issue description short, please see title.

No browser_download_url attribute present in the assets JSON here due to missing zip during release: [https://api.github.com/repos/invoiceninja/ui/releases/latest](https://api.github.com/repos/invoiceninja/ui/releases/latest)

**Comment by turbo124** [comment]
Thanks, we will look into this.

**Comment by turbo124** [comment]
this should now be resolved.
