### ISSUE TITLE
Customer Group settings missing in the new UI

### ISSUE THREAD

**Issue by vincentdh** [invoiceninja/ui#1249]
Hi,

The settings for the customer groups is missing in the react ui.  It's still available in flutter, but would be nice to have it in react also ;) 

Thanks!

**Comment by turbo124** [comment]
Which version are you on? Group settings have been in the UI for some time now

**Comment by vincentdh** [comment]
Sorry, I forgot to "docker compose up -d" after I pulled the latest version.

Keep up the awesome work! ;)
