### ISSUE TITLE
Can't add product in new invoice

### ISSUE THREAD

**Issue by greenwaym** [invoiceninja/ui#1268]
Steps to reproduce:
- Add new Invoice
- Select Customer (first error: just a limited list of customers can be selected)
- Add Product (second error: no way to add Product, instead there is a loading icon)
![Screenshot 2023-10-30 194600](https://github.com/invoiceninja/ui/assets/103878409/604a247e-a8d6-4f57-8400-449cbe4b71ff)

Using hosted InvoiceNinja with the React Web UI

**Comment by turbo124** [comment]
Hi There,

If you navigate to the customer list and select the customer and then click New Invoice, this is a work around until a fix is pushed up.

cc @beganovich @Civolilah
