### ISSUE TITLE
Translation: add_item results in wrong translation within german

### ISSUE THREAD

**Issue by paulwer** [invoiceninja/ui#1312]
the translation-property add_item translates in germany to "Artikel hinzufügen". Which means like a purchaseable item or a basked like item or simmilar. But not line or element.
When used in places like Tasks, we dont add items to be purchased and therefore you better use "Element" (elements) or "Zeile" (line) instead.

I think a complete replace to "Zeile hinzufügen" should be the way to go.

**Comment by turbo124** [comment]
@paulwer currently we use `add_item` as the translation string for both Product and Tasks. 

If we were to add an additional one for to differentiate, which would make the most sense

`add_line`
`add_task`
`add_service`

**Comment by paulwer** [comment]
within the task i would recommend to use add_line.
(because a task contains mutiple time-frames and not multiple tasks or services)

**Comment by turbo124** [comment]
I've merged this here,

#8989

it will take a while to propagate => transifex => then be updated in the app.
