### ISSUE TITLE
v5's dark theme colors have insufficient contrast for hyperlinks and some buttons

### ISSUE THREAD

**Issue by nekohayo** [invoiceninja/ui#1356]
After upgrading my Pro v4 SaaS account to v5, I was able to test the dark theme (although it is not automatically enabled based on the system's theme, invoiceninja/admin-portal#424), however the color palette is bad for accessibility. For example, right on the dashboard page, the "Recent payments" table:

![image](https://github.com/invoiceninja/admin-portal/assets/479401/efe61c6e-816a-46d5-9c08-ac035fc8d415)

This table row has a multitude of color problems (which can probably be seen in various other places in the InvoiceNinja UI):
* The hyperlinks are medium-dark blue on a dark blue background, which provides terrible contrast. They should be a brighter sky blue (like Firefox does in its articles Readability mode), a bit closer to white.
* The white row divider lines are, ironically, waaaaay too bright and contrasty. They're not supposed to be the thing grabbing my eyes here. The dashboard's revenue "Overview" graph also has what seems like very bright grid lines, I suspect it will distract from the visuals.
* White text on a bright-green button (or white on light blue, for example: ![image](https://github.com/invoiceninja/ui/assets/479401/2ae8eb05-da84-4748-8674-e5c310faa79e)) also fails to be readable. Black text on that type of bright button, or darker button background colors, please. But not _too_ dark because then you end up with this situation where your button totally blends into the background:  
![image](https://github.com/invoiceninja/admin-portal/assets/479401/3292527f-ffcc-41f8-a9b7-a70ffc2afc31)

You can easily avoid such problems by using [this](https://flathub.org/apps/org.gnome.design.Contrast). It would be good to use that tool to review all the theme colors used throughout the UI.

**Comment by nekohayo** [comment]
Some clickable symbolic icons used for actions throughout the UI, such as the delete icons in the task details' rows, are also pretty much invisible:

![image](https://github.com/invoiceninja/ui/assets/479401/809fa249-e831-42af-92dc-5fe29032634c)

**Comment by turbo124** [comment]
![image](https://github.com/invoiceninja/ui/assets/5827962/e7d8db73-00a6-4c80-b512-1982507dd1b8)

Thanks, i'm going over the dark mode and correcting these.
