### ISSUE TITLE
Task details' "Status" field could indicate live running time and provide the Start / Stop / Resume button directly

### ISSUE THREAD

**Issue by nekohayo** [invoiceninja/ui#1360]
v4's time tracker had this very nice "obvious in your face" indication that time is running in your current task, with an easy way to stop (or Resume) it with one click:

![image](https://github.com/invoiceninja/ui/assets/479401/8ef769e8-1916-4422-ae43-f5cdb2c782aa)

v5's task editor buries this into a menu, but particularly in the task's details / time records view, there would be a lot more space available to bring this functionality back:

![image](https://github.com/invoiceninja/ui/assets/479401/3e8b1136-34f8-44d9-8354-8fa020c76d1d)

I think that would make it more discoverable and readily accessible. It would also help prevent me from "forgetting to stop the clock" (which can happen quite often).

**Comment by turbo124** [comment]
[Screencast from 11-29-2023 02:38:09 PM.webm](https://github.com/invoiceninja/ui/assets/5827962/82b76385-0876-43cc-8145-955429e2e2b4)

Thanks for the feedback, in the next release....
