### ISSUE TITLE
v5 regression: impossible to create a running task with start time that started in the past, or to adjust start time, or append from end time

### ISSUE THREAD

**Issue by nekohayo** [invoiceninja/ui#1361]
In v4's time tracker, the "start time" and "end time" fields were very flexible in allowing you to create, adjust or append-resume a running task. In v5, from what I can test with my pro account in the SaaS version, the running task's current time entry is shown like this:

![image](https://github.com/invoiceninja/ui/assets/479401/3d804a35-6f0e-4185-99e0-269190834168)

That end-time, instead of leaving the digits blank when empty, shows an arbitrary and seemingly nonsensical "12 h 30 mins", which... doesn't even end after the start time in the screenshot above. And if I try to get rid of it, it messes things up.

That said, more importantly, there are three kind of scenarios/workflows I could do before, but can't anymore:
* Without needing to click the Start/Resume button: create a new running time entry ("Add item") and set its start time to sometime in the past (ex: setting it at 14h30 while it is currently 16h30) and hit the "Save" button to directly create a running task that started 2 hours ago _and keep it running_ live (with [live indications in the status area](https://github.com/invoiceninja/ui/issues/1360))
* After clicking the "Start" button (instead of clicking "Add item"), change the start time of the newly created currently running task and hit "Save" to update the currently running task (this is another variant of the usecase above)
* In a stopped task, the ability to clear the "end time" of the last time entry and "Save" the changes to resume that task _by appending to that existing time entry_ (this is needed when, for example, I stopped a task too soon or by mistake, and change my mind a few seconds/minutes later; in that case I want to be able to reuse and resume the existing last entry, not create another entry)

It would be very useful to have this kind of flexibility again. Currently the new UI "fights me" instead of adapting its running timers to match what I mean.

**Comment by turbo124** [comment]
Which browser are you using?

In chrome and firefox, this is what i see

![image](https://github.com/invoiceninja/ui/assets/5827962/e6d2bf1c-31df-4236-bfc2-8cab094b0d2d)

**Comment by nekohayo** [comment]
Also, if you create a new time entry in a task, select the date field, which is currently "2023-11-30", select the "11" month part to type "08" in its place (in order to eventually set some arbitrary date in August), it... resets it to UNIX Epoch, i.e. 1969-12-31. SaaS v5's behavior is really quite broken all across the fields.

**Comment by turbo124** [comment]
This last one is a bug where we are using onChange instead of onBlur. I've included a fix for the next release.

**Comment by nekohayo** [comment]
Should I record a screencast with all the ways I manage to break those time entries / time tracker, or have you been able to reproduce the other issues?

**Comment by turbo124** [comment]
I think we have the fix from moving to onBlur.
