### ISSUE TITLE
Reassigning a task to a different project does not trigger a recalculation of either project's total counted hours

### ISSUE THREAD

**Issue by nekohayo** [invoiceninja/ui#1375]
In my v5 Pro SaaS account, I created a new project alongside an existing one for one of my clients, and edited one of the tasks to remove its assignation from project A to project B... but the "Total hours" in both projects is now wrong:

The old project's total hours count did not go down:

![image](https://github.com/invoiceninja/ui/assets/479401/c27e1c08-077f-4859-bb93-a9a82267fa34)

The new project receiving the task indicates "Total hours: 0"

![image](https://github.com/invoiceninja/ui/assets/479401/76615eda-67a8-49be-8fcd-f8cb5fd15c52)

**Comment by turbo124** [comment]
This particular column is updated async on a 5 minute schedule.
