### ISSUE TITLE
"Upcoming Invoices" show invoice from other company.

### ISSUE THREAD

**Issue by hismayilov** [invoiceninja/ui#1404]
I have one ACME INC to test scenarios, 
I realized ACME INC shows upcoming invoices from another company. 
 * Self-Hosted.
 * v5.7.59-W145

![image](https://github.com/invoiceninja/ui/assets/676555/d6297697-d663-4019-b704-8f40167d1fa3)

**Comment by turbo124** [comment]
Thanks for notifying, i see the issue here.
