### ISSUE TITLE
Only a limited number of customers can be selected when creating a new invoice

### ISSUE THREAD

**Issue by greenwaym** [invoiceninja/ui#1448]
Steps to reproduce:

- Add new Invoice
- Select Customer (error: just a limited list of customers can be selected)

The problem was fixed in  #1268, the described workaround in #1268 still works. The Problem seems to have returned since the last update. 
I am using the hosted version of InvoiceNinja.

**Comment by turbo124** [comment]
If you start typing, the system will search based on the input. Is this no longer working for you?

**Comment by greenwaym** [comment]
It wasn't yesterday, I just tried again, and now it works without a problem. That's weird. Well, it seems to be fixed :)
