### ISSUE TITLE
Custom fields default value in product is not selected when added to new invoice

### ISSUE THREAD

**Issue by greenwaym** [invoiceninja/ui#1449]
Steps to reproduce:

- Create custom field for products (dropdown)
- Add a product, select element from dropdown
- Add an invoice with said product (problem: no element in dropdown is selected)

![Screenshot 2024-01-08 110702](https://github.com/invoiceninja/ui/assets/103878409/6b2a30bc-5565-466a-969e-73d908920521)
![Screenshot 2024-01-08 110739](https://github.com/invoiceninja/ui/assets/103878409/8c606eae-5634-4920-8231-fff42349cc8a)

**Comment by turbo124** [comment]
#1453
