### ISSUE TITLE
missing activity section

### ISSUE THREAD

**Issue by techtegritycs** [invoiceninja/ui#1451]
flutter ui has a activity section in the dashbaord and on the invoice details. i dont see that in either place on the react ui. Would be nice to have. (also with load more or infinite scroll)

**Comment by turbo124** [comment]
![image](https://github.com/invoiceninja/ui/assets/5827962/36470062-ddd9-482d-8036-340653d63916)

This is available both on dashboard / invoices / clients.

From the listview, you'll just want to click on a row to trigger the overview slideout.
