### ISSUE TITLE
React Client search is bringing up client edit instead of client overview

### ISSUE THREAD

**Issue by adrianaditech** [invoiceninja/ui#1494]
as per attached clip,
in the flutter app when you searched for a client and clicked on client name it would always bring up the client overview screen which lists their invoices, quotes, etc., with a specific button to edit client at the top if desired.
however, in the react app, searching for and clicking on a client brings up only the EDIT client page without ability to see that client's invoices/history.
I realize there is a filter option on the clients page which when you click on a client from there it lets you see the overview, but
from lots of use of the react app I can say it's much more needed to change the current react client search click to take you to the client overview screen instead of client edit, as was in flutter. otherwise I have to click a lot to find that client's history.
[Video 1-29 at 11.03.webm](https://github.com/invoiceninja/ui/assets/95985011/71ebb99f-5913-4b54-942c-2ef46f8f964e)
please change react client search on click event to open client details instead of client edit

**Comment by turbo124** [comment]
https://github.com/invoiceninja/invoiceninja/pull/9214
