### ISSUE TITLE
Transactions showing \n

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/ui#1511]
Hi,
in the transactions view, there are still newlines displayed:
![image](https://github.com/invoiceninja/ui/assets/28981528/06c84834-f92d-4a3d-a960-487cf6b1aa6f)

Please fix that.

**Comment by Civolilah** [comment]
> @Civolilah can we handle this pls.

@turbo124 Sure thing. It will be fixed.

**Comment by LarsK1** [comment]
Addition: the dates are currently also not localized...

**Comment by turbo124** [comment]
@Civolilah if these two issues are resolved could you cl
