### ISSUE TITLE
Add "Create" button to edit expense screen for continued creation of expenses

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/ui#1551]
v5.8.25-W155

If you have multiple expenses to enter, it's currently quite tedious. You have to click create, enter the details, save, upload the document, and then click back then create again to create the next expense.

As a simple suggestion, it would be great to have the "Create" button under the edit expense screen so that once you have finished with that expense, you can quickly jump to creating another one without having to go back first.

![image](https://github.com/invoiceninja/invoiceninja/assets/52687659/9f505253-33fa-4995-8c81-f538ffe4d11a)

**Comment by turbo124** [comment]
@Civolilah can we have a Save and Create option similar to tax rates

![image](https://github.com/invoiceninja/ui/assets/5827962/4579f5f2-fa0a-471c-b1c9-ae70c5388ddd)

![image](https://github.com/invoiceninja/ui/assets/5827962/4c7f189c-a2f9-4f31-be6a-c8e41aa5b5de)

this would only display on the new expense page where it is an isolated Save button

**Comment by Civolilah** [comment]
> @Civolilah can we have a Save and Create option similar to tax rates
> 
> ![image](https://private-user-images.githubusercontent.com/5827962/305699216-4579f5f2-fa0a-471c-b1c9-ae70c5388ddd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNjYxOTEsIm5iZiI6MTcwODI2NTg5MSwicGF0aCI6Ii81ODI3OTYyLzMwNTY5OTIxNi00NTc5ZjVmMi1mYTBhLTQ3MWMtYjFjOS1hZTcwYzUzODhkZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMTQxODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjI4NDZlMzMyMmRhM2E4OTBmZTY4MWVjNDRiYTk2MzFlNzA2OTBmODlmNmMyZThlZDM2N2EwZDNlNDg5NjNiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PGVlOyhHeHZ1H730C9__hKYFrvjFDpIFwenFHq1-dYE)
> 
> ![image](https://private-user-images.githubusercontent.com/5827962/305699227-4c7f189c-a2f9-4f31-be6a-c8e41aa5b5de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNjYxOTEsIm5iZiI6MTcwODI2NTg5MSwicGF0aCI6Ii81ODI3OTYyLzMwNTY5OTIyNy00YzdmMTg5Yy1hMmY5LTRmMzEtYmU2YS1jOGU0MWFhNWI1ZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMTQxODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjE3ZDk0NmVmOGFkOTQxMzE0YWQzMTIxMDFiNTNmYmE3ODRlMTkyMjNlZDcxYTc3MDVkMmNmYzhiMDhhNDI0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._YtJaunE87RIluD1-nAikJBVGLCCNm77ARVSwotir0A)
> 
> this would only display on the new expense page where it is an isolated Save button

@turbo124 Sure thing, it will be implemented!

**Comment by turbo124** [comment]
#1552
