### ISSUE TITLE
No Pagination in Group Clients List (only show 10)

### ISSUE THREAD

**Issue by Buzzmovies** [invoiceninja/ui#1566]
Hosted v5
Web version

When displaying the list of clients in a group, Web UI will only show 10 with no pagination options. That is not an issue in the desktop app.

![image](https://github.com/invoiceninja/invoiceninja/assets/47455886/2bbaf34b-8e83-4f6f-b3f8-d5b01899f2d7)

That is not an issue in the desktop app.
![image](https://github.com/invoiceninja/invoiceninja/assets/47455886/5ed52df8-b932-4ea3-acd9-8adddba907ae)

Thank you

**Comment by Civolilah** [comment]
@Buzzmovies Thanks for reporting the bug. Pagination for this table will be implemented.

**Comment by Civolilah** [comment]
#1567
