### ISSUE TITLE
Credit Note not shown on React but shown in Flutter!

### ISSUE THREAD

**Issue by sudanking** [invoiceninja/ui#1583]
Credit note for one client (only) not appear on React, but it is shown on Flutter.
Credit can show for other clients without problem.

![Vbn4aBvl4f](https://github.com/invoiceninja/ui/assets/434739/08047117-cf99-401a-9fc6-8544b72c92f8)

![floorp_7Ah0ha3x92](https://github.com/invoiceninja/ui/assets/434739/c2ffe743-f683-49a8-b93d-b3e6625506e3)

I use Docker self-hosted latest version

**Comment by turbo124** [comment]
what status is the credit? is it in draft?

**Comment by sudanking** [comment]
No, it is not draft. 
If it is draft will not appear in Flutter... Right?

**Comment by turbo124** [comment]
@Civolilah I can recreate this, could you please look into this.

**Comment by turbo124** [comment]
@sudanking are you able to share any more details.

ie. amount on credit remaining, if the due date has past on the credit (if set)
