### ISSUE TITLE
Settings: E-Invoicing

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/ui#1587]
Hi,
in the React UI, the current of choice of the e-invoice isn't reflected:
Flutter:
![image](https://github.com/invoiceninja/ui/assets/28981528/80bc594a-568a-48bf-927d-b5806fd97fe5)
React:
![image](https://github.com/invoiceninja/ui/assets/28981528/16c7c9bb-2077-417c-a605-a6f80ee0adf7)

**Comment by LarsK1** [comment]
Hi, 
@turbo124 @Civolilah can we please fix this bug sometimes soon?

**Comment by turbo124** [comment]
@LarsK1 this should be updated now, are you on the latest build for react?
![image](https://github.com/invoiceninja/ui/assets/5827962/bbcd9b24-3d58-44e5-ab0f-bc7d21abaf6f)

**Comment by LarsK1** [comment]
@turbo124 yep, works. Thanks - didn't check regularly. 👍
