### ISSUE TITLE
Settings: localisation

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/ui#1588]
Hi,
in the settings in the localisation tab, there is a minor issue:
React:
![image](https://github.com/invoiceninja/ui/assets/28981528/61090041-1d4b-46da-b1fb-587e3435f08c)

Flutter:
![image](https://github.com/invoiceninja/ui/assets/28981528/32ba7dac-63b3-4d4f-8dcd-08996f4bcdd0)

React is missing the option for the "Thousand"-separator, as well as the currency sign location is displayed wrong.

**Comment by beganovich** [comment]
Thanks for reporting.

cc @turbo124

**Comment by turbo124** [comment]
@LarsK1 i believe we do not show the thousand separator as we determine the input separators based on the currency/locale

Can you advise what you mean by the symbol location is incorrect?

**Comment by LarsK1** [comment]
Hi @turbo124 ,
I only reported, that in contrast to the flutter apps, the toggle for setting the thousand seperator (, / .) is missing.
If you do set this according to the local preference, that's totally okay form me.
