### ISSUE TITLE
Allow additional file types for uploading documents

### ISSUE THREAD

**Issue by mnaranjoberlin** [invoiceninja/ui#1624]
Hi y'all ...

if i could wish as mentioned here:
https://forum.invoiceninja.com/t/allow-mp3-for-uploading-documents/15620

we also produce moh (music-on-hold) and ivr (interactive voice responses) for our customers pbx. In this context, it would be nice to be able to upload mp3 files to the Documents area, but this does not seem to be possible at the moment.

Are the permitted document types hard-coded and/or is there a way to extend the list of permitted file types? Would it be possible to extend the list e.g. via a comma-separated parameter in .env?

Thanks for your beautiful work on IN!
Best regards
Marcel Naranjo
www.dig-it.de

**Comment by turbo124** [comment]
.env vars added for this to accept additional types.
