### ISSUE TITLE
React document preview shows up twice in external pdf viewer - not inline

### ISSUE THREAD

**Issue by mnaranjoberlin** [invoiceninja/ui#1627]
Hello again,

just posted in the forum
https://forum.invoiceninja.com/t/react-document-preview-shows-up-in-external-pdf-viewer-not-inline/15619

As an IN newcomer i thought it would be a good idea then to use React instead of Flutter just after my first steps the last days. So i entered REACT_APP_ENABLED=true to the .env - et voilá - after an “artisan optimize” React is now my friend :grinning:

React also “feels good” but i faced a behaviour, which has almost certainly to do with a setting, i am not aware of:

I.e. when clicking Settings > Invoice Design there is no inline preview of the design as i know from Flutter. Instead my external PDF-Viewer opens up twice with two different versions of the preview PDF. One seems to reflect the defaults (even with no logo an company details), while the other is more customized.

![Bildschirmfoto_2024-03-17_08-19-15](https://github.com/invoiceninja/ui/assets/162991984/e119dca9-bce0-4cde-ba23-f8d407d02413)

With this behaviour it is absolutely impossible to create/edit a custom design. Whenever i hit the keyboard the UI is processing the preview (which i.g. is good) and the external viewer comes up twice again.

Can you please explain and point me in the right direction?
How can i switch the preview to an inline view as known from Flutter?

Thanks in advance for your patience!

Best regards
Marcel Naranjo
[www.dig-it.de](http://www.dig-it.de/)

**Comment by beganovich** [comment]
Hi there,

It'd be super useful if you could share your browser/OS with us.

Thanks! :)

**Comment by mnaranjoberlin** [comment]
Hi @beganovich,

I'm running Firefox 123.0 (64-Bit) Snap for Ubuntu canonical-002-1.0 on Xubuntu Linux 22.04.4 LTS jammy based on debian bookworm/sid

Greetings!

**Comment by beganovich** [comment]
Would it be possible for you to try a different browser? Perhaps a Chromium-based one?

**Comment by mnaranjoberlin** [comment]
Hi @beganovich,

i did so and its indeed the view i expected.

![Bildschirmfoto_2024-03-19_17-13-38](https://github.com/invoiceninja/ui/assets/162991984/60071295-dd42-4f37-8f09-aaa2c085eff8)

Hope this info helps to get you further.
Thank you!

Best regards
Marcel Naranjo 
www.dig-it.de

**Comment by beganovich** [comment]
So it appears to be some weird issue with Firefox I assume?

I also use Firefox but it seems to be working fine here.
