### ISSUE TITLE
expose assigned user column in task list

### ISSUE THREAD

**Issue by CooperatusTeam** [invoiceninja/ui#1659]
In the Flutter UI, the "Assigned To" column can be displayed, which helps a lot when working with others on the same project. Since switching to the React UI, we've noticed that the "Assigned To" column is missing, and not exposed in the columns dropdown, either:

![image](https://github.com/invoiceninja/ui/assets/66752698/9986d955-d5a9-466d-8479-e27121f1e455)

![image](https://github.com/invoiceninja/ui/assets/66752698/b5d0d973-9cd9-4b5a-b8a6-f8a21908c33a)

We'd like to request the "Assigned To" column be exposed, so that we can add it to the task list view. Thanks!

**Comment by turbo124** [comment]
@CooperatusTeam I added this in a few PRs ago so this is just pending a tagged release
