### ISSUE TITLE
Add Copy Invoice Link button to invoice's More Actions dropdown

### ISSUE THREAD

**Issue by adrianaditech** [invoiceninja/ui#1680]
For many invoices sent out I find myself needing to get the invoice URL to include in my email response to someone who asked for an invoice, for example. Currently I have to click Client Portal and copy the URL from there which is a few extra steps.
Can an option 'Copy Invoice URL' please be included in the more actions dropdown so that this action can be done from the admin portal immediately?

![image](https://github.com/invoiceninja/invoiceninja/assets/95985011/ea217e93-fe83-4963-ae88-feb4080f7b87)

**Comment by turbo124** [comment]
we have a copy link on the invoice list now.
