### ISSUE TITLE
Option to load monaco-editor locally

### ISSUE THREAD

**Issue by Sebijk** [invoiceninja/ui#1706]
Setup

    Version: 5.8.46
    Environment: Docker

Checklist

    Edit a Custom Design and customize the Header example.
    Go to Developer Tools (F12)
    On Developer go to Network Monitor

Describe

monaco-editor is load externally from cdn.jsdelivr.net.  Not all people like this. So a option to load local would be great.

**Comment by turbo124** [comment]
can we set all dependencies that load via cdn to load locally please.

**Comment by turbo124** [comment]
@Civolilah can you toggle this to completed if done / link to pr

**Comment by Civolilah** [comment]
> @Civolilah can you toggle this to completed if done / link to pr

@turbo124 Yes, this is already resolved, so I'm moving it to done!
