### ISSUE TITLE
External CSS stylesheet dependency on IN v5 login page

### ISSUE THREAD

**Issue by sunbladehub** [invoiceninja/ui#1707]
The login page on InvoiceNinja v5 has a dependency on an external CSS stylesheet located at https://rsms.me/

@hillelcoren located the exact reference [here](https://github.com/invoiceninja/ui/blob/e63570f72440ac3c58d9351809e8c781c160c34e/index.html#L14) and [suggested](https://forum.invoiceninja.com/t/what-is-rsms-me/15762/2?u=alan) replacing the external dependency with a static import into the repo.

I ran into this dependency because I noticed the IN login page in my browser was hanging while showing “Connecting to https://rsms.me/ ...” after I restricted access to the external internet.

In general, it is probably undesirable for InvoiceNinja to reference external CSS like this because if it goes away or becomes inaccessible for any reason (cough... DNS), then **all** InvoiceNinja users will experience the hanging login page that I experienced.

**Comment by turbo124** [comment]
#1694 1694
