### ISSUE TITLE
Issue: wrong-tax labels

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/ui#1708]
Hi,
I noticed, that the tax selection show's wrong labels:
selected:
![image](https://github.com/invoiceninja/ui/assets/28981528/a6c9bc01-92a9-4ead-9bd6-f17f0dad51a3)
invoice:
![image](https://github.com/invoiceninja/ui/assets/28981528/50b6d406-caee-4d09-9d94-e6374e9c5569)

**Comment by turbo124** [comment]
@LarsK1 just to confirm, the error is on the PDF?

Is this with calculate taxes turned on?

**Comment by LarsK1** [comment]
Hi @turbo124,
no, the PDF is correct. Automatic tax is disabled. The selection dialoge is faulty.

**Comment by turbo124** [comment]
@Civolilah can we close this?

**Comment by Civolilah** [comment]
> @Civolilah can we close this?

@turbo124 Yes, we can. It has been fixed.
