### ISSUE TITLE
Client properties overview columns layout is not space-efficient for any notes longer than a short sentence

### ISSUE THREAD

**Issue by nekohayo** [invoiceninja/ui#1716]
I am using the v5 Pro SaaS version from your website.

Very rarely are my notes on a client short enough to be only one or two sentences long. Typically, my notes have details about the history with the client, evolution of rates, their accounts payable department's quirks, etc., which requires a couple of paragraphs, and often bulleted lists.

The problem is, the UI tries to stuff all that in a single narrow column (and I bet that it would try to stack both public and private notes on top of each other in the same column, if I were to write both). This is a tremendous waste of space (two thirds of the screen are wasted by empty space, and I have to scroll a lot to get to contents below):

![image](https://github.com/invoiceninja/ui/assets/479401/2e972bad-1368-457a-a685-5d82f924ecdd)

It would be much better if notes could be given special treatment to have a wider column, by combining some of the other columns that may be shorter. In the case shown above, the UI could have stacked the first three columns on top of each other and given the second half of the screen to the 4th column, and it presumably would have been all balanced and saved tons of space and scrolling.

**Comment by turbo124** [comment]
@beganovich thoughts on how we can handle this to support long form text?

**Comment by beganovich** [comment]
@turbo124 i guess we have two options.

a) limit vertical card height and make note scrollable
b) move public/private notes into separate card below this
