### ISSUE TITLE
Viewing the web version of an invoice sent to a client might mark the invoice as "Viewed"

### ISSUE THREAD

**Issue by nekohayo** [invoiceninja/ui#1719]
In the v5 SaaS version,

For an  already published/sent invoice,

1. From inside the invoice editor, click the top-right menubutton
2. Click "Client portal"

Result:
* After you have viewed the invoice "as if you were the client", the invoice's status is marked as "Viewed" everywhere in the UI.
* When you look at the global dashboard, you see in the activity that the invoice was "Viewed" by that client's name, yet it is your own IP address, so it was not the client who truly viewed the invoice.

Impersonating a client for testing purposes should probably not write data like that, unless you're making a payment on their behalf or something...

**Comment by turbo124** [comment]
The only way a document can trigger the logic to be marked as "viewed" is if the actual link from the invoice email is used.

I have not been able to replicate the description here by using any of the admin links / views for this.

**Comment by nekohayo** [comment]
Hmm... I have retested this with another invoice now, and you are correct that it does not get marked as read "through the client portal" if I impersonate a client via my own web interface.

My next hypothesis then is about something that might have gone wrong on my end when looking at the confirmation email that the platform sent to me (different from the one sent to the client), which looks roughly like this:

![image](https://github.com/invoiceninja/ui/assets/479401/3f96df75-d0f0-489e-92b6-69804b875730)

Originally my theory was that it must have been using the same link to the client's dashboard to view their invoice... but I see now that the one sent to me actually had an extra `?silent=true` at the end, which I presume this is the part that makes it avoid marking the invoice as "Viewed".

I must have clicked that link, and I presume in theory it shouldn't have marked the invoice as viewed, so maybe _somehow_ the extra URL parameter got stripped by my browser, I'm not sure why/how (it would sound a bit unlikely to me that uBlock Origin or CleanURLs would do this in this case). I was not able to properly test that hypothesis yet, because the client unexpectedly read the invoice I sent now, faster than I could test this!

**Comment by turbo124** [comment]
Ok, please reopen if you can recreate this particular issue.
