### ISSUE TITLE
Default sorting order is descending oldest-to-newest, instead of newest at the top

### ISSUE THREAD

**Issue by nekohayo** [invoiceninja/ui#1720]
From my observations while using the v5 pro SaaS version while invoicing in recent days, it seems that the default sorting order in all listviews/tables (invoices list, list of invoices in a client overview, etc.) is "oldest at the top" instead of "newest at the top".

* This seems like a badly inconvenient default for a UI that uses pagination. Rarely do you want to see the oldest stuff. Scrolling sucks.
* It takes 2 to 3 clicks to re-sort to "Newest at the top"
* Even if you re-sorted, it seems like it tends to forget that (especially if you have multiple tabs/browsers/etc.) and resets to the bad default at some point.

My suggestion would be to sort newest-to-oldest by default (when sorting by date) throughout the UI, to save your users from the hassle.

**Comment by turbo124** [comment]
@nekohayo 

The react application will remember the last sorted column/direction and then present this next time you return to the list view

**Comment by nekohayo** [comment]
Yes, but my suggestion is that it should have a better (inverted) default sorting to begin with, and also that I've seen it "forget" the sort order (haven't spent time trying to figure out exactly how, but I'd bet it might have something to do with multiple tabs or reloading or using the on-page "Back" button, or something like that maybe). From a UX standpoint, I doubt that your clients want to see the oldest things first by default for every new view.

**Comment by turbo124** [comment]
@nekohayo The oldest first issue would most likely be caused by a migration from the v4 platform where the documents had been inserted in reversed order.
