### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/ui#1746]
When I try to purchase a license in the React UI - nothing happens. The button has no link.
![image](https://github.com/invoiceninja/ui/assets/28981528/79b8d740-5117-43a5-a393-022b99804662)

**Comment by beganovich** [comment]
Hi, can you please share your environment with us and version?

I've tested in latest version and link seems to be working fine.

**Comment by LarsK1** [comment]
Hi,
it's selfhosted v14.04.2024.1.

**Comment by LarsK1** [comment]
There's also no a tag in the html
![image](https://github.com/invoiceninja/ui/assets/28981528/d7092efd-bb03-4d45-b4de-4070f73915cd)

**Comment by beganovich** [comment]
@Civolilah can you replicate?

**Comment by Civolilah** [comment]
> @Civolilah can you replicate?

@beganovich It works fine for me as well. The link for this element is actually pulled from the `VITE_WHITELABEL_INVOICE_URL` environment variable, so missing the link in the .env file can cause this issue. @LarsK1, can you please confirm whether your .env file is populated with the correct value for the `VITE_WHITELABEL_INVOICE_URL` variable?

**Comment by LarsK1** [comment]
@Civolilah no, there's no such variable in there. There also no such one in the .env.example.

To what value should I set it?

**Comment by Civolilah** [comment]
> @Civolilah no, there's no such variable in there. There also no such one in the .env.example.
> 
> To what value should I set it?

@LarsK1 The variable was probably added to the .env.example file later, which is why you're missing it. Please ensure that you have

VITE_WHITELABEL_INVOICE_URL=https://app.invoiceninja.com/buy_now/?account_key=AsFmBAeLXF0IKf7tmi0eiyZfmWW9hxMT&product_id=3

in the .env file, and it will work for you. Thanks!

**Comment by LarsK1** [comment]
@Civolilah just added it, and also run php artisan optimize. Still no luck

**Comment by LarsK1** [comment]
The variable doesn't exist here as well: https://github.com/invoiceninja/invoiceninja/blob/v5-develop/.env.example

**Comment by Civolilah** [comment]
@LarsK1 Ah, there seems to be a slight misunderstanding. The variable needs to be added to the React/frontend project. Here is the current .env.example file, which is the best reference: https://github.com/invoiceninja/ui/blob/main/.env.example. Thanks!

**Comment by LarsK1** [comment]
@LarsK1 where do I find this file in a regular install?

**Comment by beganovich** [comment]
You'll have to share with us how you get v5 working. Is it a Docker install, prebuilt ZIP or you did do everything yourself?

**Comment by LarsK1** [comment]
It's the prebuilt zip

**Comment by beganovich** [comment]
Thanks.

cc @turbo124, might be able to help us :)

**Comment by turbo124** [comment]
@Civolilah 

i think i know the issue, the link has changed:

```
https://invoiceninja.invoicing.co/client/subscriptions/O5xe7Rwd7r/purchase
```

Can we update the build for this url please.

**Comment by LarsK1** [comment]
Hi @turbo124 @Civolilah @beganovich ,
the big still exists, even though the pr is merged?

**Comment by turbo124** [comment]
@LarsK1 we are looking into it, it is in the backlog again.
