### ISSUE TITLE
401 unauthorized as a normal user when opening tasks overview: TypeError 'arguments' 'caller' 'callee' cannot be accessed in this context

### ISSUE THREAD

**Issue by DrDBanner** [invoiceninja/ui#1748]
## Setup
- Version: 5.8.54
- Environment: ZIP

## Interface
- Flutter: []
- React: [X]
- Both: []

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo?
NO
- Have you searched existing issues?
YES

- Have you reported this to Slack/forum before posting?
YES

- Have you inspected the logs in storage/logs/laravel.log for any errors?
YES - none

## Describe the bug
As a normal user when entering the tasks module (with having the corresponding user-rights) a popup message appears: "... action unauthorized ...". Creating tasks and reading tasks is possible though. Console.log has some insights. See Screenshot.

### Steps To Reproduce
Create user; Add rights to tasks and projects; login as user; open tasks module.

### Expected Behavior
Not getting the popup.

## Additional context
By giving the user admin rights the issue vanishes; Granting the user all rights possible, does not make the message disappear.

### Screenshots
<img width="1303" alt="Bildschirmfoto 2024-05-07 um 15 17 44" src="https://github.com/invoiceninja/invoiceninja/assets/25568865/3380837a-4c51-4879-984d-bec424ce5602">

**Comment by turbo124** [comment]
@Civolilah I believe here this is seen when the user has view permissions but not create permissions for the entity.
