### ISSUE TITLE
Add indication of documents to project's overview and indication in project's list

### ISSUE THREAD

**Issue by DrDBanner** [invoiceninja/ui#1750]
Projects: Currently the user has to guess if there are documents attached or not. 

### Projects List
<img width="1241" alt="Bildschirmfoto 2024-05-07 um 16 25 46" src="https://github.com/invoiceninja/ui/assets/25568865/aca7d3ed-f612-4547-a3e4-d84cf8120cd6">

Adding a symbol should be sufficient.

### Projects Overview 
<img width="1235" alt="Bildschirmfoto 2024-05-07 um 16 25 31" src="https://github.com/invoiceninja/ui/assets/25568865/153a9082-a502-4c26-97cb-b2bd85208d45">

Adding a card with a list of items would be somewhat nice. 
Optional: Add a title field to documents when uploading in order to have proper information within the card that's subject of creation here. 

Minimal option would be to add at least the document count to the summary which links to the documents pane after click.

Another option may be to have a $secondary_color pill (next to status?) with documents count to either open the documents or open them in a lightbox gallery.

**Comment by turbo124** [comment]
![image](https://github.com/invoiceninja/ui/assets/5827962/959ae809-053d-4348-96df-572106724cd9)


You can add the documents column to the project list

**Comment by beganovich** [comment]
You can change table columns by clicking Columns in the bottom right corner.

![image](https://github.com/invoiceninja/ui/assets/13711415/b59e4c69-99ad-4f6b-9c7b-d4086c5cc2bf)
