### ISSUE TITLE
Missing setting

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/ui#1768]
Hi,
we added a new option in the last PR. Could you please add that option as well? (merge_e_invoice_to_pdf)
https://github.com/invoiceninja/invoiceninja/blob/643f8a64c3bb3a41baa9ff27dda20fc08cba562a/app/Jobs/Entity/CreateRawPdf.php#L116

**Comment by beganovich** [comment]
Hi, thanks for suggestion.

@turbo124 can you please advice the next steps?

**Comment by turbo124** [comment]
@beganovich we'll need to add this in please.

**Comment by beganovich** [comment]
@turbo124 noted & added to Jira :+1:

**Comment by LarsK1** [comment]
Thanks, works like a charm!
