### ISSUE TITLE
Feature Request: UX: Button for reconnecting / refresh nordigen bank_integration

### ISSUE THREAD

**Issue by paulwer** [invoiceninja/ui#1770]
Hey folks,
a while ago we implemented the new nordigen account integration, which can be configured via the settings.
A bank_integration will expire after 90 days by default and the user have to refresh the integration.

# Current Implementation
Right now, the user has to click connect new and select their institution and then follow the workflow.

# Exspected Behavior
The user should have a button called refresh connection / refresh or simmilar, which opens the workflow to sign in again directly for him / her, skipping the bank-selection screen.

# Suggested Solution
You should have to add a button on each bank_integration item within the list which 
- redirects to url.com/nordigen/connect/<institution_id_from_bank_integration>
- is visible when the bank_integration attribute disabled_upstream is true

# Changes in flutter-app
@hillelcoren is informed and is already working on this

Thank you all <3

**Comment by turbo124** [comment]
@paulwer we use the onetime token for this currently, i would assume embedding the institution_id in that payload will have the same impact?

**Comment by paulwer** [comment]
yes it does.

**Comment by turbo124** [comment]
@paulwer looking into this, i do not see a /connect endpoint, but i do see

createRequisition(config('ninja.app_url') . '/nordigen/confirm', $data['institution_id']

is this the correct one?

**Comment by paulwer** [comment]
sorry, the correct opting of the link is as follow:

url.de/nordigen/connect/<token>?institution_id=xxxx

**Comment by hillelcoren** [comment]
When using the /nordigen/connect route to initially connect I include the hash returned by the call to /one_time_token, for example: `/nordigen/connect/$response['hash']`

Do I need to do the same thing here, so the URL would be: `/nordigen/connect/$response['hash']?institution_id=...`

**Comment by paulwer** [comment]
From my pov yes, but please talk to David, he was about to do some changes here after some discussions today.

**Comment by turbo124** [comment]
the route is /nordigen/connect/{onetimetoken}

so you would need to provide a onetime token with payload ['institution_id']

**Comment by hillelcoren** [comment]
Thanks! I've checked in a new Flutter web app and I'm working to release new mobile/desktop apps. When you have a chance please give it a try.

**Comment by turbo124** [comment]
this also works as expected in React now, closing.
