### ISSUE TITLE
available space not respected in translated customer > invoices + quotes > list view > more actions

### ISSUE THREAD

**Issue by DrDBanner** [invoiceninja/ui#1818]
Text runs over drop down list boundaries

<img width="1511" alt="Bildschirmfoto 2024-06-12 um 11 43 50" src="https://github.com/invoiceninja/ui/assets/25568865/23b1ee1e-015d-4de3-bafa-b541175d361f">

**Comment by turbo124** [comment]
@Civolilah did we have a fix in for this?

**Comment by Civolilah** [comment]
> @Civolilah did we have a fix in for this?

@turbo124 Sure, we will find a solution for this!

**Comment by beganovich** [comment]
Thanks for the report. Fix has been merged :+1:
