### ISSUE TITLE
React web app in new version 5.9.4 always uses default quantity of zero

### ISSUE THREAD

**Issue by Plaschke-Culturall** [invoiceninja/ui#1843]
Hi!

We recently upgraded our self-hosted installation to v5.9.4. and I wanted to test the react web app.

In the product settings we usually disable "Show Product Quantity" and set the default quantity to one. (We don’t deal with product quantities and we don’t show them on the invoices).
This works fine in the old flutter web interface but when I switch to the new react web app, it still shows the product quantity when creating a new invoice and this quantity is always set to zero.

How can we get rid of product quantities again?
Or at least have a default value of always one?

**Comment by turbo124** [comment]
![image](https://github.com/invoiceninja/ui/assets/5827962/eaec137f-bb44-49f2-82a8-75f486be6a74)


if you toggle default quantity to on, does this auto set the quantity to 1 for you?

**Comment by Plaschke-Culturall** [comment]
No, this property seems to get ignored, no matter what I select.

I now also have bugs with the tax-rate for items. The tax-rate that is shown in the drop-down menu after selecting one (when adding a new item) is different than the tax-rate I selected (and that is applied on the invoice).


Maybe I should just first try to somehow update my installation to the most current version v5.9.9.

**Comment by LarsK1** [comment]
Can confirm this one as well.

**Comment by turbo124** [comment]
https://www.loom.com/share/781c0ba678984adb90fc853b35f576fc?sid=b694301b-a8cc-4367-a052-ffb97eec74b9


Just to confirm, in the react app the product quantities are only hidden in the product edit page. The quantity may still display on the invoice edit form, however it will default to 1.

Are you seeing something different to this?

**Comment by LarsK1** [comment]
@turbo124 this is my default window, after adding a single line item
![image](https://github.com/invoiceninja/ui/assets/28981528/fbeec37a-244c-44dc-a5bb-c23c9ec23379)

**Comment by turbo124** [comment]
@LarsK1 

And after you select a product?

**Comment by LarsK1** [comment]
@turbo124 then it automatically set's the quantity to 1. But the request is, which makes sense to me as well to set the quantity to 1, even without a product selected. As many (so do I) don't create a product for each item, which is sold (maybe only once).

**Comment by Plaschke-Culturall** [comment]
Yes, exactly. We don't create a product for each item, because we basically have different line items everytime we issue an invoice.
So if I write a new invoice with e.g. 10 items I have to manually insert the quantity 1 everywhere, even though we don't use quantities on our invoices.

In the old app there was not even a field to set a quantity if you had "Show Product Quantity" unchecked in the product settings.

For us this would be the most convenient solution, to not have the field there on the create invoice page.
Or just set it to the default value of 1 instead of 0.00 (if that is selected in the product settings).

Not that this is a huge issue, it's just slightly annoying ;-)

**Comment by turbo124** [comment]
@Civolilah the task here is that when a new line item is clicked (+) if Set product default quantity is set to 1, then we inject 1 into quantity
