### ISSUE TITLE
Wrong text for Whitelabel

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/ui#1844]
Hi,
I recently purchased a whitelabel license for our instance, but the React interface still show's as "Free", while Flutter shows as "Licensed". I'm running the latest version available, as of now.
![image](https://github.com/invoiceninja/ui/assets/28981528/f3c64b01-7606-44b3-a81f-4176a60c6bd7)

**Comment by link470** [comment]
This happened for me as well after upgrading from 5.8.x to 5.10.13.  The license now shows "Self Hosted (Free)", even though there's an expiration date well into the future.  This doesn't seem to effect the actual generation of a non-watermarked Invoice; the application _does_ appear to be correctly whitelabeled.

**Comment by Civolilah** [comment]
> This happened for me as well after upgrading from 5.8.x to 5.10.13. The license now shows "Self Hosted (Free)", even though there's an expiration date well into the future. This doesn't seem to effect the actual generation of a non-watermarked Invoice; the application _does_ appear to be correctly whitelabeled.

@link470 We made a fix for this one, and it will be correctly displayed for you in the next release.
