### ISSUE TITLE
Custom Fields No Longer Display in Details Section

### ISSUE THREAD

**Issue by mfernald** [invoiceninja/ui#1848]
Custom Fields no longer display without going into Edit.

See screenshot below:
<img width="785" alt="Screenshot 2024-06-19 at 11 05 56 AM" src="https://github.com/invoiceninja/ui/assets/36588547/bf91b82d-5eda-4e65-8d5f-cc86488f6d6f">

They still appear in desktop application

**Comment by turbo124** [comment]
@Civolilah 

If a value exists, we'll also want to display this on the company overview.

**Comment by Civolilah** [comment]
> @Civolilah
> 
> If a value exists, we'll also want to display this on the company overview.

@turbo124 Okay, it will be added to the client and company overview.
