### ISSUE TITLE
contact selected but not show on table.

### ISSUE THREAD

**Issue by Kingwayer** [invoiceninja/ui#1854]
while creating table like PO, already selected contact from one vendor it's should displayed on table but not, see screenshot.

![123](https://github.com/invoiceninja/ui/assets/171299849/0e01a8e6-4866-43e4-be51-8d66418bd7dc)

![bb](https://github.com/invoiceninja/ui/assets/171299849/fddd148a-aacd-4e92-9555-4ef506d96993)

**Comment by turbo124** [comment]
![image](https://github.com/invoiceninja/ui/assets/5827962/08774dea-f2d0-4d06-92a3-0e7db3380a6e)

Have you added the vendor contact to the invoice design?
