### ISSUE TITLE
products image url not showing ( see screenshot attached)

### ISSUE THREAD

**Issue by Kingwayer** [invoiceninja/ui#1856]
there is no preview for product image, just want know when/where it's shows?
if I want  preview from product page or thumbnail on some tables like invoice/quote, how to do it?

![picture](https://github.com/invoiceninja/ui/assets/171299849/ccd367d0-38f9-4f16-a007-e33ca05597cc)

**Comment by turbo124** [comment]
This is just a URL, you can use <img> tags to reference this and display the image.
