### ISSUE TITLE
Hide new user option when selecting user for Gmail/Microsoft Sending.

### ISSUE THREAD

**Issue by dylanh724** [invoiceninja/ui#1857]
## Setup

Hosted with you. Web app only (since no desktop support, it seems).

## Describe the bug

When I choose GMail (OAuth) email provider **user**, the dropdown says the list is empty. I expected to find my own (since I login with Gmail - it's already connected).

When I go to the only option (new user), I'm asked to upgrade to enterprise, detecting it as a completely different user. I should be able to select the user I'm already logged in with (or asked to connect my gmail, if not already connected).

### Steps To Reproduce
1. https://app.invoicing.co/#/settings/email_settings
2. Email provider == Gmail (OAuth)
3. Dropdown gmail user

OAuth is the recommended flow rather than smtp, so smtp is probably the temporary workaround.

### Expected Behavior

I should be able to add my own user rather than forced to arbitrarily create another new user.

### Screenshots

![image](https://github.com/invoiceninja/invoiceninja/assets/8840024/288d8778-c75e-4ae0-8c35-8696fb480ffe)

**Comment by turbo124** [comment]
![image](https://github.com/invoiceninja/ui/assets/5827962/68e036cd-c76f-495f-9f88-0522442f4b5a)

We should not show the new user option here when selecting the sending user.
