### ISSUE TITLE
custom fields not copied , wrong quantity values

### ISSUE THREAD

**Issue by datformatie** [invoiceninja/ui#1870]
webapp v14.04.2024.1 problem: custom fields are not copied when creating invoice from products.. also quantity field is set to 0 (in flutter desktop is works and quantity field is set to 1..)

[Slack Message](https://invoiceninja.slack.com/archives/C9KSLL0TE/p1719561072830579)

**Comment by turbo124** [comment]
When using  the new invoice from the product action, the custom values are not copying over.

**Comment by datformatie** [comment]
Hi There, any developments on this bug? It renders the webapp when using customfields unusable....

**Comment by turbo124** [comment]
once it has been tagged as a bug, it is on our backlog to be fixed.

**Comment by datformatie** [comment]
thnks!

**Comment by datformatie** [comment]
since v5.10.11 it is not possible to NOT use react (i.e. UPDATE accounts SET set_react_as_default_ap = 0;) Since this bug is still unresolved we like to switch to Flutter admin portal....but question is "how do we achieve that goal?"
