### ISSUE TITLE
Feature request: Button to add tasks/products to invoices in React UI

### ISSUE THREAD

**Issue by exstntlmsnthrp** [invoiceninja/ui#1874]
Hello.

I've been using IN for my small consulting business for about 18 months now and it's brilliant. I have recently switched from using Flutter to using the the React UI, given that we've been told on the forum that Flutter will eventually be removed. Overall, the React UI is great and I feel an improvement over Flutter. However, there is a major UI feature that is missing for me in the REACT UI.

As a consultant, I do not sell any widgets or any type of product. I use tasks extensively (and exclusively) for time tracking and billing of my clients. When creating an invoice in the Flutter UI, there is a + (plus symbol) in the lower right corner that enables you to import completed tasks into that invoice. 

![Flutter-desktop](https://github.com/invoiceninja/ui/assets/57594290/0e0e2fc1-49ad-47e1-9b9e-b426655a27da)

When using the React UI, this does not exist.

![React-invoice](https://github.com/invoiceninja/ui/assets/57594290/96a94e4d-167b-4855-9848-14a6aaf40dc3)

***I would like to request that something like this is implemented within the React UI.***

For me, this is an extremely convenient feature that is now missing. In Flutter, I can click the + (plus symbol) and then select all of the tasks related to that client. Unless I am missing something in React, I have to go in and manually recreate each task, which is tedious and inconvenient.

**Comment by turbo124** [comment]
To confirm, this would allow a user to select uninvoiced tasks for the client to be imported.
