### ISSUE TITLE
[BUG] Rendering bugs with Templates

### ISSUE THREAD

**Issue by Braunson** [invoiceninja/ui#1879]
When I try to edit my Payment template, it doesn't load the body at all but it does show a preview as if there was?

![2024-07-04-17201294751](https://github.com/invoiceninja/ui/assets/577273/8203d426-28f9-4d84-bd66-bf768fe69cd9)

Another issue is using the new Web UI is when editing the Statement template, it looks like $start_date and $end_date are in the template but never get compiled and show the exact same string in the rendered preview.

Same as above goes for the vendor in the template Purchase Order.

**Comment by turbo124** [comment]
I'm not able to replicate this. Are you able to use the three dot menu, then <> menu option and advise the text that is included in that window? for some reason it is not populating in the tinymce window.

**Comment by Braunson** [comment]
Checking the tinymce code (as per your instructions) shows nothing in the source code popup textarea.

I am seeing a JS error in the console but it's seemingly unrealated:

```console
@sentry-bfeb32cd.js:5 Failed to load plugin: mceCodeEditor from url plugins/mceCodeEditor/plugin.min.js
```

**Comment by turbo124** [comment]
how have you installed the application? this looks like a resource is not loading.

**Comment by Braunson** [comment]
This is using the new web UI version in Chrome, no apps installed.

**Comment by turbo124** [comment]
@Braunson How have you setup the app? ie softaculous, docker, release file etc etc.

**Comment by Braunson** [comment]
I have not, I pay InvoiceNinja to have this hosted. I originally reported this on discord and was sent here.

**Comment by turbo124** [comment]
@Braunson sorry, you should not have been sent here, i'll look into this for you, ping us contact@invoiceninja.com and we can dive into this a bit more.
