### ISSUE TITLE
Duplicating invoice does not correctly fill tax rate

### ISSUE THREAD

**Issue by atymic** [invoiceninja/ui#1881]
Repro steps:

1. Check invoice you are duplicating, note tax rate selected and applies 
![Screen Shot 2024-07-08 at 10 24 44@2x](https://github.com/invoiceninja/ui/assets/50683531/a86e9c48-370e-4d7d-a1cb-37276f932996)
3. Duplicate invoice, see shown cloned version copies most things, but missed applying the tax rate
![Screen Shot 2024-07-08 at 10 25 34@2x](https://github.com/invoiceninja/ui/assets/50683531/e5205842-5a23-4247-9084-cf24383db7e0)

Mis invoiced a couple of times due to this, as the old flutter UI correctly clones tax rates.

Thanks :)

**Comment by turbo124** [comment]
@Civolilah we'll want to ensure the line items / taxes etc are brought over on clone

**Comment by atymic** [comment]
Line items work, it's just the tax rate doesn't seem to apply.

**Comment by atymic** [comment]
Thanks 🙏
