### ISSUE TITLE
v5.10.5 and v5.10.6 CSS stylesheet fails MIME check and not loaded

### ISSUE THREAD

**Issue by Bitals** [invoiceninja/ui#1883]
Before posting please check our "Troubleshooting" category in the docs: 
https://invoiceninja.github.io/docs/self-host-troubleshooting/
This is a 404

## Setup
- Version: v5.10.5 or v5.10.6
- Environment: Docker

## Interface
- Flutter: []
- React: [x]
- Both: []

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo?
No, it runs 5.9.9.
- Have you searched existing issues?
Yes
- Have you reported this to Slack/forum before posting?
No
- Have you inspected the logs in storage/logs/laravel.log for any errors?
Yes, but they don't seem to be relevant here.

## Describe the bug
Upon loading the page styling is broken and an error is logged into browser console.

### Steps To Reproduce
1. Run v5.10.5 or v5.10.6
2. Launch React app

### Expected Behavior
CSS style sheet MIME type is set correctly (text/css) and is therefore loaded and applied by browsers

## Additional context
Tested with both Firefox and Chromium, same behavior.
This was not a problem before v5.10.5.

### Screenshots
![image](https://github.com/invoiceninja/invoiceninja/assets/11341915/65ac0381-f181-417d-942a-c688ecf50ec5)

### Logs
Firefox:
```
The resource from “https://<domain>/index-63ab4581.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```
Chromium:
```
Refused to apply style from 'https://<domain>/index-63ab4581.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

**Comment by turbo124** [comment]
as you can see from the screenshot, firefox is detecting the mime-type correctly as a css file. If you are using a reverse proxy, then mostly like the problem is there as it may not be setting the appropriate mime's Here is another screenshot of my docker container 

![image](https://github.com/invoiceninja/ui/assets/5827962/1444d6d8-dab8-426c-8858-8a11c3048c13)


Also, if you inspeact the page source, you can clearly see that the css is being referenced in a standard way:

![image](https://github.com/invoiceninja/ui/assets/5827962/0b8324b4-559e-437d-8cea-923f99237122)

**Comment by Bitals** [comment]
@turbo124 reverse proxy only adds the `contentTypeNosniff` header, which is an industry standard. But it does not set the file MIME type returned by the backend. Doing so would be straight up malware behavior.
I am pretty sure it's just forced to `true` by browsers nowadays, as setting this to "false" in `traefik` does not allow it to load with the same error.

This behavior is not present in the image from Dockerhub. Is it built from a different source? Docker builds are supposed to be reproducible. Not necessarily byte-to-byte, but functionally for sure.
I am building the image from https://github.com/invoiceninja/dockerfiles/tree/5.10.8/alpine/5

And just closing this issue is weird. Am I supposed to buy the product that immediately tells me to go away the moment some non-trivial issue arises?

**Comment by turbo124** [comment]
If you can prove the issue is within invoice ninja please reopen. We are unable to reproduce the issue.

**Comment by Bitals** [comment]
Am I expected to learn Laravel to report an issue?

Anyway, thanks for your immense help. For anyone with the same issue - the solution was to rebuild the last image with cache disabled. So seems like the problem got introduced in `v5.10.5` as an either version-specific side-effect of something else or as a one-off docker build anomaly, but got stuck in the docker cache locally.

**Comment by turbo124** [comment]
I do not believe it is a laravel issue at all. I believe this to be an environment issue. It appears that your "rebuild" fixed the issue, given it is transient, only localized to your environment (and currently with no other reports) I'm unsure how we would be responsible for this?

**Comment by Bitals** [comment]
Point about Laravel was about debugging. This file is not present in the directories mounted from the repo by default, so at least pointing to where to look for it, at what step it is generated etc. would go a long way.
I never asked to go to my environment and fix everything for me. But as I had no familiarity with Laravel and no pointers, I had to try things blindly, which is surprising for me considering the product asks me to buy a license on every page of the UI.

This is what influences the buying decisions.

**Comment by turbo124** [comment]
This particular issue has nothing to do with framework at all, laravel / react.

If you observe the screenshot above you can see that we simply display the CSS link. How your browser / container delivers and renders this is well outside our scope of responsibility.
