### ISSUE TITLE
React, v5.10.6 - .env file and self update check

### ISSUE THREAD

**Issue by BloodyIron** [invoiceninja/ui#1884]
Hi @turbo124 after switching to the DockerHub image v5.10.6, and then to the React web app, the health check reports:

![image](https://github.com/invoiceninja/invoiceninja/assets/12439391/dc5fceeb-b775-4d97-9b04-eb1b3abcbc3b)

And when I touch ".env" in ~/ the error goes away, but InvoiceNinja doesn't seem to ever put anything in that file. Not sure if this is giving me problems but just thought you would want to know.

Also, I'm getting dev console errors on page loads, specifically about self update check (remember I'm using the dockerhub image in kubernetes so that's where the updates come from), sanitised screenshot:

![image](https://github.com/invoiceninja/invoiceninja/assets/12439391/f15923bb-2ad3-4246-aa0e-43d7ee65d95c)

Again not sure if either are causing me problems, but might be working against me for speed or other things.

As for initial page load speed that seems to be tied to the /api/v1/refresh step in the page load with a load time of ~1.79s.

Anyways, hoping all this helps you help us all :)

**Comment by turbo124** [comment]
@Civolilah 

in the system health check we have a flag:

`is_docker`

This determines if the user is running the application in a container.

If set to true, we should hide the Permissions section of the health check as it is redundant.

**Comment by turbo124** [comment]
tracking this one here: #1869

**Comment by BloodyIron** [comment]
> We'll need to adjust the output of the health check on Docker as the file permissions issue is redundant in a docker container.
> 
> As for the check_version error, that would be an issue with your container reaching https://pdf.invoicing.co/api/version to get the latest version of the app, you may want to see if you can resolve this domain from within your container.
> 
> lastly, how large is your dataset, 1.79 seconds does not sound that bad if you have a large dataset, as the refresh query is very large, and the payload may be significant.

1. Do those health checks extend "correctly" when this image is used in Kubernetes?
2. I don't have anything blocking resolution to that FQDN, and I just ping'd inside the container, it resolves to a public IP. But why can't that just be included in the docker image itself? I really want this to be 100% self-hosted and not reliant on external services like that. What if that endpoint/service goes down for whatever reason for short or long periods of times? Permanently?
3. I really don't think my dataset is large by any stretch of the imagination, I would classify it quite small. We're talking like tens of invoices and tens of clients, and not much more than that.

**Comment by BloodyIron** [comment]
Anyways, thanks for your help again! :)

**Comment by turbo124** [comment]
@BloodyIron 5.10.8 has an additional performance improvement on startup, i'd be interested to hear if this version resolves your performnce issues.

**Comment by BloodyIron** [comment]
> @BloodyIron 5.10.8 has an additional performance improvement on startup, i'd be interested to hear if this version resolves your performnce issues.

@turbo124 

The situation does not appear to be tangibly improved, and I confirmed it's reporting "API: 5.10.8" so I'm on the latest image (also confirmed that the latest image was pulled).

So I'm not really seeing anything new, but to give some more insights of what I am seeing, there's two noteworthy parts to the earlier parts of the page loading. First some stuff that is blocking rendering, and then two parts immediately after that. I am not 100% sure on all the things included in the "second part" so to say.

First, these aspects are blocking rendering (I think) until they complete, and they take a while to complete:
/api/v1/refresh
/api/v1/statistics
combined they take about 1.7s, report they are in bundle.js:143, and yeah block any rendering until they complete

Then right after they complete the page starts rendering, and the most predominant next lines (maybe others?) I can see are:
/api/v1/self-update/check_version
663ms, and produces HTTP 500
then
/api/v1/health_check
8.38s, but this looks like maybe it's getting deferred and loads later, I'm not sure.

It's not so clear beyond that what else is slowing things down but maybe we can start with these.

Thanks for your help as always :)
