### ISSUE TITLE
BUG: Pushing 'Back' button in Tasks creates new task

### ISSUE THREAD

**Issue by exstntlmsnthrp** [invoiceninja/ui#1895]
I have recently upgraded to v.5.10.8. After creating and saving a new task, clicking the back button creates a new task and does not go back to the list of tasks.

![Invoice-Ninja-Edit-Task(1)](https://github.com/user-attachments/assets/a4c10a88-1e1f-490e-b229-1a954559b6b8)

API: 5.10.8
UI: React
Browser: Firefox & Chrome

If you need any additional information, please let me know.

**Comment by turbo124** [comment]
the back button is haunting me.

**Comment by exstntlmsnthrp** [comment]
Hahaha and sorry.

**Comment by beganovich** [comment]
Hey there, we decided to move forward integration of breadcrumbs as they're very clear UX.

Closing as fixed in #https://github.com/invoiceninja/ui/pull/1898.
