### ISSUE TITLE
[Feature-Request] Document upload

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/ui#1904]
Hi,
can you please implement an upload field for e-documents (like XInvoice in the document section). See https://github.com/invoiceninja/invoiceninja/pull/9635

**Comment by turbo124** [comment]
@LarsK1 just to confirm on this one. Did you want to import a einvoice? Was there a specific area you wanted this to be implemented? my thoughts are this could work in the "import" green button on the invoice list page?

**Comment by LarsK1** [comment]
Hi @turbo124 ,
it would definitely go onto the expenses screen. Not sure, if I would add a second box to the import button or rather add a space to drag-and-drop in the main overview, since every click needs time, especially for larger companies which may have thousand of invoices to handle each day.

**Comment by LarsK1** [comment]
Hi @turbo124 ,
any ETA on this one? This must be ready until January 1st or better in October, so that enough people can test and validate until the governmental deadline...

**Comment by turbo124** [comment]
@Civolilah 

can we add XML upload. to the import screen please on expenses

![image](https://github.com/user-attachments/assets/4f3b2b08-974f-4ddb-982f-15d4e2249097)

this can take multiple files attached to the 'documents' prop

route => edocument/upload

**Comment by turbo124** [comment]
@LarsK1 i've bumped this up the list.

**Comment by turbo124** [comment]
@LarsK1 

I am testing this functionality now and am seeing some issues with the import mechanism, are you able to share a sample .xml file I can use to test here please?

**Comment by LarsK1** [comment]
@turbo124 see here https://github.com/invoiceninja/admin-portal/issues/669#issuecomment-2293189606

**Comment by turbo124** [comment]
@LarsK1 thanks, confirmed working using that file, available in the next release.
