### ISSUE TITLE
Make the “Columns” button look like a button

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/ui#1907]
Next the the pagination buttons, there’s a “columns” button that let’s you customize which columns are shown in the table above.

![image](https://github.com/user-attachments/assets/1965cf0a-d3d2-4408-8591-6e9bcfac7b7c)

Unfortunately, it doesn’t really look like a button; instead it appearance is rather similar to the “row” **label** that is found next to the row-count selection on the left.

I’d prefer if this button looked like an actual button, so that the feature (that it enables) can be found in a more convenient way on the page.

#### Background info

I was wondering where the  “client number” column hat gone that was there in the Flutter frontend. It looked like it had been replaced with the not-in-use-by-us “register number”…

That weird label “columns” next to the arrow got me curious. Initially I suspected a rogue translation here, but got a positive surprise. Turns out, one can customize the columns. Very nice feature, thanks for that! (Please make it more visible, though.)

**Comment by turbo124** [comment]
@beganovich  I've seen a few reports on this one, we'll want to improve the UI around this one.

**Comment by beganovich** [comment]
Thanks for reporting, this should be better in next update :+1:
