### ISSUE TITLE
Would it be possible to have an ability to enter time manually, like it was with https://invoicing.co/?

### ISSUE THREAD

**Issue by theoryshaw** [invoiceninja/ui#1909]
In https://invoicing.co/ you could enter in times...

https://github.com/user-attachments/assets/d3e392a0-95d1-472a-ab07-7a147faa56ae

It's seems in https://app.invoicing.co/ you have to pick the hour/min/secs?
Would it be possible to have an ability to enter time manually, like it was with https://invoicing.co/?  Saves a lot of time. 

![image](https://github.com/user-attachments/assets/eb0dd019-bcae-4f0b-b780-a241420851b4)

**Comment by turbo124** [comment]
@beganovich is it possible to accept user input on this?

**Comment by beganovich** [comment]
Hi there, we can look at this and possibly do it using preferences/settings.

**Comment by LarsK1** [comment]
Hi @theoryshaw ,
i can input the just fine. just click into the field and enter the time in HH:MM:SS. Works perfect for me

**Comment by theoryshaw** [comment]
@LarsK1 Hmm, you're right. I swear I tried to do this before, and it wasn't accepting what i was typing in.  It does now. Thanks.
Close?
