### ISSUE TITLE
After creating an invoice, and picking the client, that i would offer a list of projects to pick from...

### ISSUE THREAD

**Issue by theoryshaw** [invoiceninja/ui#1910]
I would assume if i go to...
`https://app.invoicing.co/#/invoices/create`

And when i select a client, that it would then allow me to pick a project, as well. 

mockup...

![image](https://github.com/user-attachments/assets/47ace51a-4473-4127-91c6-69d49ea01b09)

**Comment by turbo124** [comment]
![image](https://github.com/user-attachments/assets/fead69a4-9068-48be-9678-1ca5c535a5e0)

**Comment by theoryshaw** [comment]
Thanks David.
for consistency would recommend putting the project field under the client field like other UI interfaces.
