### ISSUE TITLE
IN tar releases - Workflow react UI stuck on v14.04.2024.1 

### ISSUE THREAD

**Issue by DrDBanner** [invoiceninja/ui#1925]
## Setup
- Version: Latest
- Environment: Tar

## Interface
- Flutter: []
- React: [x]
- Both: []

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo?
No idea

- Have you searched existing issues?
No

- Have you reported this to Slack/forum before posting?
Yo

- Have you inspected the logs in storage/logs/laravel.log for any errors?
No

## Describe the bug
UI build workflow doesn't seem to trigger when building new releases.

### Expected Behavior
Having the lastest UI release build in published IN tars

## Additional context
NONO

### Screenshots
<img width="1198" alt="Bildschirmfoto 2024-07-24 um 10 20 07" src="https://github.com/user-attachments/assets/b7411790-7b9a-4616-803a-d21cce0b74af">

### Logs
NoNo

**Comment by turbo124** [comment]
resolved for the next release.
