### ISSUE TITLE
.env file is not writable by the current user

### ISSUE THREAD

**Issue by barcelona92** [invoiceninja/ui#1927]
Hi,
I install invoice ninja selhostd v5 in DOcker, all ok , but in Health check option appear this in the last option:

PERMISSIONS.
env file is not writable by the current user.

![b3N71XG](https://github.com/user-attachments/assets/bd408615-7e2c-4c72-b1f5-f9dd29ac65ed)

**Comment by turbo124** [comment]
Tracking this one here:

#1869
