### ISSUE TITLE
Setting Groupspecific default tax with 0% doesnt work

### ISSUE THREAD

**Issue by ret1** [invoiceninja/ui#1929]
## Setup
- Version: 5.10
- Environment: Docker

## Interface
React

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo?
same error on the react UI, its working on the normal demo and the desktop application.

- Have you searched existing issues?
yes

- Have you reported this to Slack/forum before posting?
yes. [https://forum.invoiceninja.com/t/setting-groupspecific-default-tax-with-0-doesnt-work/16629](https://forum.invoiceninja.com/t/setting-groupspecific-default-tax-with-0-doesnt-work/16629)

- Have you inspected the logs in storage/logs/laravel.log for any errors?
no

### Steps To Reproduce
im trying to setup invoice ninja for my company and was unable to set a “Group” specific default tax when its 0%. if i select a customer which is in that group, while creating a new invoice, the name of the tax changes according to the group specific defualt tax, but the tax itself doesnt switch to 0%. if the group specific tax is set >0%, everything works as expected. also, after selecting another tax, the values gets corrected.

in this case “Ustr” should be 0%

![screenshots](https://github.com/user-attachments/assets/4bc7a7b6-10c5-4df9-b96b-84fd266d35c3)

### Expected Behavior
the tax (inclusive tax rate) should be set according to the group setting for the default tax

**Comment by turbo124** [comment]
@Civolilah The issue here is if the group tax is 0% the company tax will always override.
