### ISSUE TITLE
On the Clients page, Number and ID Number columns are both "ID Number" in the table

### ISSUE THREAD

**Issue by link470** [invoiceninja/ui#1931]
On the Clients page, the _Number_ and _ID Number_ columns have the same name of _ID Number_ in the actual table.

After the upgrade from 5.8.x to 5.10.13, I noticed the _ID Number_ column in the table had no value, but it did before.  I then added the column _Number_ and a new column appeared, also called _ID Number_, that contained the client's number.  The _Number_ column in the columns settings should also be called _Number_ in the table, otherwise if both _Number_ and _ID Number_ are selected, you'll see two columns with the same name.

![IDNumber](https://github.com/user-attachments/assets/d2f184f4-54e4-4dc6-991e-707cdb2365c4)

**Comment by turbo124** [comment]
thanks, fix checked in here

#1933
