### ISSUE TITLE
Application version numbers not consistent after 5.8.x to 5.10.13 upgrade

### ISSUE THREAD

**Issue by link470** [invoiceninja/ui#1934]
The version numbers after upgrading to 5.10.13 don't match what's on the [InvoiceNinja Releases](https://github.com/invoiceninja/invoiceninja/releases) Github page.  Previously, in the Flutter UI, I'd see a version number of 5.8.x.

On the InvoiceNinja login page, or going to About within the app, I see v14.04.2024.1, as shown below.  Nowhere do I see 5.10.13 as the application version.

![Version](https://github.com/user-attachments/assets/604974ea-e86d-4cd4-9f3e-b9d72c884dd0)

The only thing I can think of is that maybe the v14.04.2024.1 version was being used specifically for React, but it still seems odd to me to have the overall application release as 5.10.13 and then the in-app version be 14.04.2024.1.

**Comment by turbo124** [comment]
5.10.13 is the API version
the version in the about is the react version.

**Comment by link470** [comment]
> 5.10.13 is the API version
> the version in the about is the react version.

That was my guess.  Could both be added to the About screen in that case?  Something like:

Version 5.10.13
React Version 14.04.2024.1

That seems cleaner to me since all my years before running 5.10.x I've always had the version number shown in About match the version number shown in the InvoiceNinja releases.

**Comment by turbo124** [comment]
If you click on the Health Check, you'll get additional information, including the API version.

**Comment by gaetan-hexadog** [comment]
I agree. It's strange to bury the API version when it used to be front and center for so long as the main application version.

- Is the `API` supposed to be used alone without UI ?
- If so is there a process to update API and UI distinctively ?
- Wouldn't be better to display both versions at the same place ?

I tried to click on the Health Check but there is no API version either. How can I now which version is currently running ?

![CleanShot 2024-08-18 at 12 07 23@2x](https://github.com/user-attachments/assets/2d1b9932-c285-49cc-a773-e9cb02e22a63)

**Comment by turbo124** [comment]
> I agree. It's strange to bury the API version when it used to be front and center for so long as the main application version.
> 
> - Is the `API` supposed to be used alone without UI ?

Yes

> - If so is there a process to update API and UI distinctively ?

N/A

> - Wouldn't be better to display both versions at the same place ?
> 

We can add the API version here also.

**Comment by gaetan-hexadog** [comment]
Thanks @turbo124.
My questions was here to try to understand the need to have 2 distinct versions for end-user.

If we can't install API alone or UI alone and if we can't update them distinctively then I don't see why having 2 different version numbers.

In a technical point of view I completely understand it but for a (non developer) end-user there is no need to have 2 different versions - it's even confusing

**Comment by turbo124** [comment]
The react app is bundled as a convenience for self hosted users who wish to run the self update function within the app.

This is only available when the API version changes. There is no version numbering of the react app for this build.

**Comment by gaetan-hexadog** [comment]
So why displaying the react version in the about instead of the API version ?
