### ISSUE TITLE
Can't add Dashboard charts after upgrade from 5.8.x to 5.10.x

### ISSUE THREAD

**Issue by link470** [invoiceninja/ui#1935]
I upgraded from 5.8.x to 5.10.13, which I believe made React the default UI.

I was looking for a way to modify my dashboard, so I navigated to Settings > User Details > Preferences.  When I scrolled to the bottom, I noticed something odd.  There's a section for _Dashboard charts_, but the only option is to remove two options in here.  There's no option to add anything, and no description of what this is.

![image](https://github.com/user-attachments/assets/3d0f6fb3-8ef7-48e7-a150-0aec2f4fe15a)

If I remove the two entries that are there, the section disappears entirely, until I click Cancel at the top, bringing the _Dashboard charts_ section back and returning the two items I had in here.

This almost seems like something that was from the Flutter UI and isn't used anymore, but somehow is displayed in the React UI until the items are removed.

**Comment by turbo124** [comment]
These are used to determine the defaults used for the charts on the dashboard. This section allows the user to remove the configuration back to defaults.
