### ISSUE TITLE
Cannot reliably update names of items on the fly

### ISSUE THREAD

**Issue by itkfm** [invoiceninja/ui#1938]
In the React frontend, it’s not always possible to rename items.
The updated name is not used for the PDF. Nor does it get saved when hitting the save button.
…When this happens.

### Workaround

One has to delete the item from the quote and add a new one with the same data but the correct name.

### Screenshot + steps

Please note that this does **not** occur all the time.

See this screenshot taken on *react.invoicing.co*.

1. Create new quote.
2. Add item with a wrong name was created (“Gulasch” in the case of the screenshot).
3. Hit [Save]
4. Rename the item. (Maybe to “Gulasch 2”.)
5. Hit [Save]
6. The change is neither reflected in the PDF preview nor in the quote.

![image](https://github.com/user-attachments/assets/e363c040-b713-4508-a6ee-cde8f23841ef)

**Comment by itkfm** [comment]
Hint: There’s a higher chance to reproduce it, when you leave the item-name field by a mouse click than using the keyboard.

**Comment by itkfm** [comment]
![image](https://github.com/user-attachments/assets/63638f49-049e-4ce6-beb5-345253cd8650)

**Comment by itkfm** [comment]
Looks like a databinding is not triggered when you leave the field by clicking somewhere else on the page.

----

I recommend clicking somewhere here for more reliable reproduction of the issue:
![image](https://github.com/user-attachments/assets/60350241-f66e-47c5-9b9c-c593698d0ad0)

**Comment by turbo124** [comment]
I can recreate this.


@Civolilah  steps to reproduce enter in any data into the line items.

Then remove some characters just from the Item field and click save. The PUT request contains the old  data, not the updated item text.
