### ISSUE TITLE
Errors when adding Stripe API keys (new installation)

### ISSUE THREAD

**Issue by mryanbc** [invoiceninja/ui#1946]
When adding the Stripe Keys (live or demo) to a new install, it gives an error 'something went wrong' or even '404 | Nothing to see here!' on the web react.
On the desktop app it instantly works however.

**Comment by turbo124** [comment]
Is this the only place you are seeing this particular error? I am unable to recreate this.

**Comment by mryanbc** [comment]
Yes only here. Also does not seem to be anything in the logs.

**Comment by turbo124** [comment]
Is the issue when you click save, or click on the health check? I can replicate when creating a new stripe gateway and then clicking health check prior to save cc @Civolilah

**Comment by mryanbc** [comment]
When I click save. Helath check show nothing that could lead to a cause for this
