### ISSUE TITLE
Incorrect currency display selection in v5.10.17

### ISSUE THREAD

**Issue by mikulabc** [invoiceninja/ui#1947]
It seems that a setting was forgotten in the new design,

The previous had it correctly, on the right side you can see the localization settings showing € and EUR when EUR is selected, on the left side the newest version has some generic $ USD showing, by purpose?

![image](https://github.com/user-attachments/assets/320dca54-7d7c-4aa0-bbde-83b730195468)

![image](https://github.com/user-attachments/assets/74d34938-bee9-4fa2-9672-cca28bd20ba3)

**Comment by turbo124** [comment]
I believe we only use the $ as an example of where the placement will be.

In the app, you will have the exact currency selected however.

**Comment by turbo124** [comment]
@Civolilah can we change the symbol / code to match the currently selecting currency in Settings > Localization.
