### ISSUE TITLE
Task details editor's "running" timer does not correct itself when changing the currently running task's start time

### ISSUE THREAD

**Issue by nekohayo** [invoiceninja/ui#1965]
If you edit a task to start its running timer, and later in the day want to correct the start time for it (either to make it start earlier, or to make it start later because you got sidetracked or delayed by something else), editing the field and clicking "Save" does not correct the running timer.

For example, if the running timer is now at 4.5 hours, and you bump today's start time 2 hours later, the timer remains at 4.5 hours+ after saving the changes. Only a full page reload corrects it.

Tested with the v5 pro SaaS version on Firefox 128.

**Comment by turbo124** [comment]
time should be recalculated on save.
