### ISSUE TITLE
Another "UNIX epoch time reset" glitch when deleting parts of timecodes in task details' timelogging fields

### ISSUE THREAD

**Issue by nekohayo** [invoiceninja/ui#1968]
Similar to issue #1718 and #1361, but still occurs as of today in the Pro v5 SaaS version:

https://github.com/user-attachments/assets/5c39fd42-709d-4239-bb15-989695939375

**Comment by turbo124** [comment]
@Civolilah never allow the start time to reset, always set the default to 00:00:00

If the end time is available, then ensure when it loses focus that there is a valid time set, else discard the change that was made.
