### ISSUE TITLE
Reports time range dates fields don't interpret what I mean, and reports export button breaks forever after error message

### ISSUE THREAD

**Issue by nekohayo** [invoiceninja/ui#1970]
Tested with the Pro v5 SaaS version, two issues in one here:

1. It does not "parse what I mean" when I simply type the month in the field. It already knows what I mean, after all it had that placeholder text in the background of the field! Why can't it understand that I meant to change only the month, and that if I left the year (or some other part of the date) incomplete then it could assume this year? (same for "this month" etc.)

2. As soon as you hit that error message, it's Game Over, the "Export" button will never work again until you reload the page and start over

https://github.com/user-attachments/assets/9491745c-990b-4ab7-95ad-a9b36dc8368f

**Comment by turbo124** [comment]
need to handle the 422 here and reset the action buttons.
