### ISSUE TITLE
Some modules are failing after upgrade

### ISSUE THREAD

**Issue by geniqtech** [invoiceninja/ui#1980]
## Setup
- Version: 5.10.21
- Environment: Self Hosted

Updated from version 5.10.13 to 5.10.21 today but some modules failed to work correctly after that.
Affected modules (will display blank empty page):
- Invoices
- Recurring Invoices
- Quotes
- Credits

JavaScript error caught on console
SyntaxError: The requested module './bundle412.js' does not provide an export named 'p' (at bundle405.js:1:354)

**Comment by beganovich** [comment]
Hi there,

Can you try reloading a browser without a cache? (CTRL+Shift+R on Chrome)

**Comment by geniqtech** [comment]
@beganovich Ctrl + Shift + R does not seem to work but after manually deleting cached images and files, it works again.

**Comment by turbo124** [comment]
In 5.10.24 I have implemented cache busting for this.
