### ISSUE TITLE
I would assume after I 'invoice project' from a specific project that it would auto-populate the invoice with this project.

### ISSUE THREAD

**Issue by theoryshaw** [invoiceninja/ui#1986]
I would assume after I 'invoice project' from a specific project that it would auto-populate the invoice with this project.
Perhaps i'm missing something. 

https://github.com/user-attachments/assets/fa349be4-413a-4746-b22f-330b63c2b4d8

**Comment by turbo124** [comment]
@theoryshaw no, the client should be populated when the project is created. My guess is that the client record is not available at this point @beganovich @Civolilah please advise.

**Comment by turbo124** [comment]
@theoryshaw one thing that may impact this is if the task inside the project has already been invoiced? you would not be able to re-invoice the project?
