### ISSUE TITLE
Add more items to the "Category" Dropdown in Expenses

### ISSUE THREAD

**Issue by Connexiumlabs** [invoiceninja/ui#2005]
I would like the ability to have more than 20 items in the "Category" Dropdown of the Expense page.

Currently, the "Vendor" Dropdown does not seem to be limited in such a way.

Thank you for your consideration.

![image](https://github.com/user-attachments/assets/53cc61a2-5bfb-4877-907f-5da6307540c7)

**Comment by turbo124** [comment]
@Civolilah 

I note that on the expense_categories route, we do not have a per_page in place meaning the default of 20 i used. Could we please increase this to 500 to match the vendor route.
