### ISSUE TITLE
Old Payments on Dashboard - react Web UI

### ISSUE THREAD

**Issue by woodlawntech** [invoiceninja/ui#2008]
On the web UI dashboard (v Latest Build - 2024-08-15), in the recent payments section, it is showing the first 50 payments (i.e., oldest), instead of the latest 50.

**Comment by turbo124** [comment]
By default the recent payments will be sorted by payment date descending, however this list is also sortable. The app remembers your last sort order, so if you have previously filtered and re sorted this particular list, you will have that sorting as your default until you change this again.

cc @Civolilah
