### ISSUE TITLE
Display failure in React app

### ISSUE THREAD

**Issue by sjmdia** [invoiceninja/ui#2032]
Hi i found yesterday this display failure

![image](https://github.com/user-attachments/assets/2e9ae187-d8bb-426f-86b2-c9346bb54e53)

**Comment by turbo124** [comment]
@Civolilah can we scale using prefixes? 1000,00 1k ?

**Comment by Civolilah** [comment]
> @Civolilah can we scale using prefixes? 1000,00 1k ?

@turbo124 We encountered a similar issue much earlier, so I covered this edge case by quickly improving the existing logic we had for calculating the y-axis width. Thanks!

**Comment by turbo124** [comment]
@Civolilah ok great, can you link the PR to this issue for autoclose on completion please ;)
