### ISSUE TITLE
Option to require confirmation for retrospective editing (modifying invoices that have already been sent)

### ISSUE THREAD

**Issue by ttytm** [invoiceninja/ui#2035]
Retrospective editing of processed invoices might cause issues or is prohibited in some countries, so it can be good to require an additional confirmation step when editing an invoice that has already been sent.

There where similar request about immutability of sent invoices. Though I think there are situations where editing invoices is desired, and full immutability would cause conflicts. The mentioned setting might be the right middle ground and sufficient for the users looking for such a feature.

An option in the settings could allow to enable to require additional confirmation. 

*Example of a Modals content if such a setting is enabled*

---

> ### Retrospective editing

> [!WARNING] 
> Please note: If this receipt has already been sent to your customer or processed further, you could incur tax law disadvantages if you process it retrospectively. Instead, cancel and duplicate this receipt (recommended).

> <kbd>Edit anyway</kbd> <kbd>Cancel</kbd>

---

**Comment by turbo124** [comment]
@ttytm 

We have lock invoices functionality for this exact purpose.

**Comment by ttytm** [comment]
Thank you for letting me know about this option, I didn't knew about it.

So if they are locked via the environment variable, it looks like there is no chance for a middle ground. I was hoping for that extra security while still generally having the ability to edit invoices. A warning modal is what providers such as sevdesk or lexoffice do. Maybe this classifies the issue as a feature request, otherwise it can be closed.

Thanks again I appreciate the help :bow:

**Comment by turbo124** [comment]
@ttytm 

you could disable this setting - perform your edits - then turn this one back on as needed.
