### ISSUE TITLE
"Tax Exempt" toggle not taking effect when set for the client and "Calculate Taxes" is turned on

### ISSUE THREAD

**Issue by adrianaditech** [invoiceninja/ui#2040]
When "Tax Exempt" toggle is enabled for a client, and "Calculate Taxes" is turned on under _Settings>Tax Settings_, taxes are still being applied (following global settings) on new invoices created for this client.
Expected behavior is for NO taxes to be added by default to invoices created for the client when their "Tax Exempt" toggle is on.

Issue type: bug

**Comment by turbo124** [comment]
@Civolilah the task here is if the client is tax exempt, we do not insert _any_ taxes at the line level or total level. This overrides all other configuration we have in the UI>
