### ISSUE TITLE
web version: you cannot select the 'created by' field in the Task report

### ISSUE THREAD

**Issue by Karmanoid** [invoiceninja/ui#2043]
If you choose the Task report and go to the field settings, there is no option to display the 'created by' column. 
However, this option is available in the desktop application.

**Comment by beganovich** [comment]
@turbo124 does this functionality depend on the API changes?
Flutter app probably exports locally.

**Comment by turbo124** [comment]
@beganovich we'll need to add to the task map user and assigned user

**Comment by turbo124** [comment]
#2094

**Comment by beganovich** [comment]
Thanks, this will be fixed in next release :+1:
