### ISSUE TITLE
create task: filter project list when client is selected

### ISSUE THREAD

**Issue by CooperatusTeam** [invoiceninja/ui#2060]
_(Filing this task based on the suggestions here: https://forum.invoiceninja.com/t/creating-task-client-has-no-connection-with-projects/16955)_

When using the deprecated Flutter UI to add a new task, the projects list is filtered by the selected client. This doesn't happen in the React UI, which leads to confusion when a project associated with a different client is accidentally selected.

In my test data below, the projects have been named in such a way that demonstrates which client they are associated with, but in production this is almost never the case. Often there are even projects with the exact same name associated with different clients, making it impossible to determine which one to select when creating a task.

#### Old (Flutter) behavior

To illustrate how it worked under Flutter, when no client is selected, all projects show in the dropdown:

![image](https://github.com/user-attachments/assets/4e56c30f-d2c9-4d0c-b5b2-aa4fa4e3faea)

When a client is selected, the projects shown are limited to those associated with that client:

![image](https://github.com/user-attachments/assets/b22b8d0f-18c3-46b6-987a-6ee0da37b814)

#### New (React) behavior

With React, the project list is unfiltered when no client is selected, matching the Flutter behavior (aside from sorting):

![image](https://github.com/user-attachments/assets/f034fb7f-4573-4150-8a5b-51465d659fd4)

However, when a client is selected, the project list is still unfiltered:

![image](https://github.com/user-attachments/assets/4e75e3e8-0b14-4fc6-9637-f426b3255dcb)

#### Request

If possible, it would be ideal if the available projects were filtered to only show the ones associated with the selected client.

**Comment by turbo124** [comment]
@Civolilah IF a client is selected, we'll need to ensure that the ?client_id=XXXXX is pass into to the URL for project list to ensure the list is correct.

We'd also need to invalidate the project query if the client is removed to ensure the project list always matches the client selected.
