### ISSUE TITLE
Setting / updating transaction amount fails

### ISSUE THREAD

**Issue by CodeShakingSheep** [invoiceninja/ui#2083]
## Setup
- Version: 5.10.29
- Environment: Self-hosted .tar

## Interface
- Flutter: []
- React: [x]
- Both: []

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo? **Yes**
- Have you searched existing issues? **Yes**
- Have you reported this to Slack/forum before posting? **No**
- Have you inspected the logs in storage/logs/laravel.log for any errors? **No**

## Describe the bug

When creating a new bank transaction with whatever amount, the correct amount is not saved. It's always 0.

When updating an existing bank transaction, although IV states "Successfully updated transaction" the amount isn't updated but still has the old value.

Both is reproducible on the React demo instance.

### Steps To Reproduce
Just create a new transaction and see that the amount is saved with 0.

Just update an existing transaction's amount and see that the old amount is still present.

### Expected Behavior

The amount value should be saved correctly.

## Additional context

Created this transaction and tried to update the amount from 0 to 7,000 - not working. https://react.invoicing.co/transactions/k8mepY2aMy/edit

### Screenshots

![Screencast from 2024-10-01 16-16-29](https://github.com/user-attachments/assets/ff51fb7e-edb1-4314-b5de-12fab1c02ddb)

### Logs

```

```

**Comment by turbo124** [comment]
@CodeShakingSheep thanks for reporting, I can replicate this.
