### ISSUE TITLE
Updated invoice item title is not updated in PDF preview

### ISSUE THREAD

**Issue by CodeShakingSheep** [invoiceninja/ui#2084]
## Setup
- Version: 5.10.29
- Environment: Self-hosted .tar

## Interface
- Flutter: []
- React: [x]
- Both: []

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo? **Yes**
- Have you searched existing issues? **Yes**
- Have you reported this to Slack/forum before posting? **No**
- Have you inspected the logs in storage/logs/laravel.log for any errors? **No**

## Describe the bug

When updating an item title in an invoice, sometimes the item title is not updated in the PDF preview. It happens sometimes not always.

### Steps To Reproduce

Update an existing invoice item's title and check if it's updated in the PDF preview.

### Expected Behavior

The PDF preview should display the updated item title.

## Additional context

Tried to update first item's title of this invoice https://react.invoicing.co/invoices/wMvbmOeYAl/edit from "Quas." to "Quas.qus". Wasn't updated in the PDF preview. See screenshot gif.

### Screenshots

![Screencast from 2024-10-01 17-34-36](https://github.com/user-attachments/assets/c9cd6205-0604-4eed-9ac7-6b7ad96a90da)

### Logs

```

```

**Comment by turbo124** [comment]
I can recreate this also, i also cannot consistently reproduce it.. it only impacts when modifying an existing item / renaming.

Also, when the preview does not update, and you save, the change is not saved... so it appears to be something with the input itself not updating its value

**Comment by beganovich** [comment]
Thanks, this will be fixed in next release :+1:
