### ISSUE TITLE
Can't save a quote without entering a value in the "Discount" field

### ISSUE THREAD

**Issue by Ph03n1ks** [invoiceninja/ui#2110]
I'm unable to save a quote until I enter a value in the "Discount" field.

![CleanShot 2024-10-08 at 19 06 00@2x](https://github.com/user-attachments/assets/e1b44db3-8604-47b5-981a-646a86fd41eb)

_Invoice Ninja 5.10.31, Docker_

**Comment by turbo124** [comment]
should be resolved in .32
