### ISSUE TITLE
"Mark sent" is an invalid selection for draft quotes when selected via the Action menu

### ISSUE THREAD

**Issue by Ph03n1ks** [invoiceninja/ui#2113]
**Invoice Ninja 5.10.32, Docker**

I tried to change the state of a draft quote to "Sent" using the checkbox in the quote list view and then choosing the "Mark sent" item via the Action menu at the top, but it throws an error. The "Mark approved" choice works fine for draft quotes.

![CleanShot 2024-10-09 at 10 01 00@2x](https://github.com/user-attachments/assets/28e2368a-20a2-4a87-ba1a-c7d8ddd1d6c7)

**Comment by turbo124** [comment]
@Civolilah the action should be mark_sent not sent for this.
