### ISSUE TITLE
Tax Rate remains applied to payment gateway when disabling Invoice Item Tax Rates

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/ui#2121]
v5.10.34-W171
Self Hosted

### VIDEO explaining and demonstrating:
https://youtu.be/m0_BL8dBuSs

If you enable Invoice Item Tax Rates, you then have the ability to add a tax rate to a payment gateway (such as square).

I have inclusive taxes enabled in settings.

I enable Invoice Item Tax Rates:
![image](https://github.com/user-attachments/assets/46648295-bb2e-465e-bc5f-ad015ffe6c7d)

I then chose 10% tax rate for the Square payment gateway:
![image](https://github.com/user-attachments/assets/93ab6e88-1a6c-4e19-95a2-32ba064d7e8d)

The result works as expected.

However, if I then go into settings and disable Invoice Item Tax Rates, the tax rate that was applied to the payment gateway **remains set in the database,** even though the field to set the tax rate on the payment gateway has now disappeared (because we disabled Invoice Item Tax Rates). This could create problems where now we have disabled Invoice Item Tax Rates and yet the tax rate we set on the payment gateway is still being applied, **even though the field is no longer visible to the user.** This results in the 

Expected behaviour: If Invoice Item Tax rates is disabled, then clear any set tax rates for payment gateways.

**Comment by turbo124** [comment]
If a user disables item or invoice taxes. Any previous invoices that have these set will not show those taxes set. This can create confusion for the user later when there are unexpected values that are not shown.

The solution here would be to present a banner notification stating that previous configured taxes are hidden with a CTA to the tax_settings screen for the user to change the type and # of taxes  displayed.
