### ISSUE TITLE
Ability to add $project to  email templates - FEATURE REQUEST

### ISSUE THREAD

**Issue by exstntlmsnthrp** [invoiceninja/ui#2131]
As a consultant, I often have clients with whom I am working on multiple projects at one time, as well as clients that have multiple ongoing projects within their organization.

It would be extremely helpful to be able to include `$project` within the email template setting so that a specific project name can be included in either (or both) the email subject and/or body.

Thanks for considering this!

**Comment by turbo124** [comment]
$project.name is available for use. The invoice needs to be linked to the project

**Comment by exstntlmsnthrp** [comment]
Thanks for the clarification. I could not find it in the documentation. Additionally, I was trying to use $project and didn't realize it needed to be $project.name. That worked perfectly. Thanks.

**Comment by turbo124** [comment]
@exstntlmsnthrp 

just for reference, these variables should be available:

https://invoiceninja.github.io/en/custom-fields/#custom-fields
