### ISSUE TITLE
[BUG] Task-time-details faulty

### ISSUE THREAD

**Issue by n1smithy** [invoiceninja/ui#2142]
Using Docker on version 5.10.41

Only (hopefully) in the React-web-app task-time-details are faulty in invoices after creating an invoice out of a task:
![grafik](https://github.com/user-attachments/assets/5c0de587-07a9-4b74-8fc5-881d443fe4e1)

1. Localization is set to 24 hours, but it's formated into AM/PM
2. Sometimes the sum of the times is 0 when it should be > 0

**Comment by turbo124** [comment]
@Civolilah can you ensure that we are formatting - throughout the app - that is 24hr time is enabled, we format all times using 24hr time please

![image](https://github.com/user-attachments/assets/92be7c91-2d15-4b47-9419-7d6b94aecd48)
