### ISSUE TITLE
Expense category options not displaying in drop down menu when entering expense (repeat bug)

### ISSUE THREAD

**Issue by TekWarren** [invoiceninja/ui#2151]
## Setup
- Version: latest
- Environment: docker

## Interface
- React: []

## Describe the bug
This is a repeat bug although I can not find the previous post I submitted here or on the forum:
Expense Category drop down is not displaying the full list of options. I am able to start typing the name of the other options and then I can select the corresponding item. 

### Steps To Reproduce
Create new expense having multiple expense categories, click drop down option, only one item is displayed. 

### Expected Behavior
All expense categories displayed in drop down menu. 

## Additional context
I can't find my previous report of this but seemed like a quick fix. I can reproduce this in two different local instances, also cleared browser cache/cookies same result. 

### Screenshots
Can add if requested.

**Comment by turbo124** [comment]
Can you provide the screenshot from the headers tab as well please. we'd need to see the full URL

**Comment by Civolilah** [comment]
@fanvyr Hey, I just checked the behavior of the Expense Selector that you're having issue with. We have some tests made for this selector, and for testing certain edge cases, we used the `VITE_IS_TEST` environment variable. I'm not sure why it's set to "true" by default in your `docker` setup. This variable can cause the dropdown to show just one item instead of all of them. If the `VITE_IS_TEST` variable is set to "true" in your `.env` file, that would explain what you're experiencing.

Please let me know if I can help you with anything else.

**Comment by fanvyr** [comment]
Hey, 

thanks for the Feedback. 

@turbo124 
Sorry, cannot give you the full Headers Tab, but the full URI i can give you (except my selfhosted-url ;-)
```
/api/v1/expense_categories?status=active&per_page=1&sort=name%7Casc&filter= 
```

@Civolilah 
How you're figuring the VITE_IS_TEST is set to ```true``` ? 
I'm using [Cloudron](https://www.cloudron.io/) for deploying. I just checked the .env file, and the ```VITE_IS_TEST``` is not listed there at all. I will though add it and set it to false, to try it. Will update this post. 

Thanks Guys

**Comment by TekWarren** [comment]
Just wanted to pop in here and say thank you to those who have added to this issue. It's nice to see some traction on an issue that was dismissed and I have been just dealing with since reporting the second time. 

I am following the conversation and will try to provide additional information if possible/needed.

**Comment by fanvyr** [comment]
@Civolilah 
Thanks for your help and guidance. 
I've checked and there are indeed only 4 Products in the Report list. So the env-var should solve it. 
But now im confused, which env file to edit. 

Can you give me a hint in which folder to look? 
I got everything in the /app folder. There is `code` , `data` and `pkg` 

Here's the `code` folder: But all those .env files seems to be the wrong ones. 

![app-code-folder](https://github.com/user-attachments/assets/ef6c39a0-7bde-4831-a079-f430b874cb12)

Here's the `data` folder:

![app-data-folder](https://github.com/user-attachments/assets/b0c4f614-364c-4bce-ac32-c12daed91949)


The public folder is empty.

**Comment by turbo124** [comment]
I've tested this locally, i think the URI is missing some additional data, my request looks something like this:

```
http://dv5r.test:8009/api/v1/expense_categories?status=active&per_page=1&filter=&with=Wpmbk5ezJn
```

note the `with=` this is exact ID of the category, and it is also the reason why the per_page=1 because there is only one expected result.

**Comment by fanvyr** [comment]
@turbo124 
I don't fully get how you're connecting this here. If the `with` parameter is present, wouldn't it then be right to get only one result? As I here WANT all (or lets say the normal 20), then the `with` parameter should not be present right?

**Comment by turbo124** [comment]
@fanvyr sorry, i see this now. Appears to only be impacting Docker installations @Civolilah 
![image](https://github.com/user-attachments/assets/0e96c7b4-5986-4fa6-966d-1eee257fd806)

The network tab shows some very odd network calls to the /expense_categories route. First a call for ?per_page=100, followed by per_page=1

Non-Docker
![image](https://github.com/user-attachments/assets/89d5ef8d-d3a7-4578-aa60-07cc783ebd3e)

**Comment by fanvyr** [comment]
Well, we already figured out that the `VITE_IS_TEST` is somehow set to `true` based on the reports page. But I cannot figure out how to properly set it to false. Be reminded, I'm hosting it via cloudron.

**Comment by turbo124** [comment]
@fanvyr the issue is not  on your side, i believe the pipeline we use to produce the build has it set to true by default.

**Comment by beganovich** [comment]
@turbo124 not that I know about. We'll switch to VITE_IS_TEST=false by default & update the CI.

**Comment by fanvyr** [comment]
> update

Perfect. Can you let me know when its done? 

Thank you so much

**Comment by TekWarren** [comment]
I guess I'm out of the loop a bit, was my report confirmed a bug and now fixed or do I need make some manual change to correct?

**Comment by turbo124** [comment]
fix has been merged, available next release.

**Comment by TekWarren** [comment]
Thank you!!

**Comment by fanvyr** [comment]
Works now :) Thank you all so much.

**Comment by TekWarren** [comment]
> Works now :) Thank you all so much.

I haven't updated yet but thanks for helping get the details the devs needed!
