### ISSUE TITLE
React Web App | Tasks | Status and state columns show the same data

### ISSUE THREAD

**Issue by Skarema** [invoiceninja/ui#2154]
React Web App

Tasks -> `Status` and `State` columns show the same data.

![CleanShot 2024-10-31 at 14 29 57@2x](https://github.com/user-attachments/assets/68055606-042d-41a7-892c-10672cace883)

**Comment by Skarema** [comment]
Both filter fields are called `Status` 🤔

The value `Logged` doesn't exist in any of the select fields.

![CleanShot 2024-10-31 at 16 26 22@2x](https://github.com/user-attachments/assets/aaec54fd-8d1e-432c-a226-4e12b17a45aa)

**Comment by turbo124** [comment]
![image](https://github.com/user-attachments/assets/43be8c76-03d5-4374-9011-2246c6774d29)

**Comment by turbo124** [comment]
only the status is filterable, not the "state"
