### ISSUE TITLE
React Web App | Task hours only printing "0,00 Hours"

### ISSUE THREAD

**Issue by Skarema** [invoiceninja/ui#2155]
Invoicing tasks with the option print hours enabled, only prints `0,00 Hours`.

![CleanShot 2024-10-31 at 14 35 31@2x](https://github.com/user-attachments/assets/0d91be2c-6e0f-4b6b-ab0c-10bb1e185ab3)

**Comment by turbo124** [comment]
can you provide a redacted view of tasks showing the hours/time there please.

**Comment by Skarema** [comment]
This is a screenshot of the timelogs of the above task:
![CleanShot 2024-11-01 at 13 59 50@2x](https://github.com/user-attachments/assets/a48f6204-9be4-41ea-a84c-aa8ce85f0e54)

This is a screenshot of the full invoice including other tasks (the one above is the second task on the invoice):
![CleanShot 2024-11-01 at 13 56 06@2x](https://github.com/user-attachments/assets/4ba1ed19-0d5f-4cbb-9e2d-f0924317c19f)

**Comment by Civolilah** [comment]
@turbo124 I've tried many ways, but I'm not able to recreate this issue. It seems to be showing correct behavior on my end. Screenshot:

<img width="387" alt="Screenshot 2024-11-07 at 15 38 16" src="https://github.com/user-attachments/assets/c6ff5a14-b9b3-43a3-a51d-7fdded4155df">

Are you able to reproduce @Skarema 's behavior when invoicing tasks or adding tasks to an existing invoice?

**Comment by turbo124** [comment]
@Skarema 

Is this consistently happening for you, or only isolated to this invoice?

We just need a way to recreate the issue to push a fix in.

**Comment by glennbossitbe** [comment]
Hi,

I'm facing the same problem. It is only when you invoice directly from Tasks. When invoice through the project the counter is working as expected.
My project is running for multiple months and I would like to invoice monthly.

**Comment by Civolilah** [comment]
> Hi,
> 
> I'm facing the same problem. It is only when you invoice directly from Tasks. When invoiced through the project the counter is working as expected. My project is running for multiple months and I would like to invoice monthly.

@glennbossitbe I understand the issue you're experiencing, but it has already been resolved. You're not seeing the resolution yet because production hasn't been updated with the changes. However, production will be updated soon and you won't experience this issue anymore.
