### ISSUE TITLE
Invoice Status missmatch

### ISSUE THREAD

**Issue by Skarema** [invoiceninja/ui#2156]
There is a status called `Sent` but I cannot seem to filter for this status.

![CleanShot 2024-10-31 at 16 22 14@2x](https://github.com/user-attachments/assets/0c14a46d-0e35-497e-b92d-880c6cdbfc90)

**Comment by Skarema** [comment]
![CleanShot 2024-10-31 at 16 28 14@2x](https://github.com/user-attachments/assets/1039551b-0ada-46e2-a518-a9141aa92c78)

Both are called `Status`

**Comment by turbo124** [comment]
If a status is past due it is also sent.

**Comment by turbo124** [comment]
do you mean Sent as in Emailed, or sent as in the status is sent?

Any invoice that is not draft is "sent"
