### ISSUE TITLE
Client portal registration currency's

### ISSUE THREAD

**Issue by HandsOfGod2** [invoiceninja/ui#2175]
## Describe the bug
Client portal registation shows texts.currency_ before all currency's 

### Steps To Reproduce
Open client registration page. 

### Expected Behavior
Not to have texts.currency_ before all currency's 

### Screenshots
 
![Screenshot 2024-11-09 165525](https://github.com/user-attachments/assets/e3f7ec5e-f8e7-4a76-be04-78f45167afad)

### Logs
Log's are clear.

**Comment by turbo124** [comment]
![image](https://github.com/user-attachments/assets/66057d23-b1dd-4642-b690-04a9c784e604)
I cannot recreate this, is this occuring for a specific locale?

**Comment by HandsOfGod2** [comment]
Not country. Currency

**Comment by turbo124** [comment]
Fixed in main repo here: https://github.com/invoiceninja/invoiceninja/pull/10231
