### ISSUE TITLE
Remove Version Number from Login Screen

### ISSUE THREAD

**Issue by link470** [invoiceninja/ui#2176]
On the login screen of Invoice Ninja, the version number is shown as _v Latest Build_ and then the build date, as shown below:
![image](https://github.com/user-attachments/assets/68a9d1b4-e9b3-4005-9fc2-243f94e03201)

While this version doesn't correctly show the actual version number (as was fixed for the About window within the web app), it shouldn't even be here at all because it gives an unauthenticated visitor access to the version of the code under the hood, which isn't advised for security.  The version number should be removed from the login screen and only displayed in the About window once authenticated in Invoice Ninja.

**Comment by turbo124** [comment]
Can you explain the security risk associate with this?

**Comment by link470** [comment]
By having the version displayed on the login page, it gives any unauthenticated visitor looking for vulnerabilities into the code the exact version of the product you're running.  If I was a hacker, I'd see, for example "oh, this site is running version 5.10.26...great, let's go check what security issues there were in that version that weren't patched yet and take advantage of them".

By having the version number not displayed publicly, it removes the ability for an attacker to know what code you're running behind the scenes, which would otherwise give them free information about the underlying code and a chance to look for published vulnerabilities.

It's an easy thing to remove to increase security, while still displaying the version internally on the About screen for authenticated users.

**Comment by link470** [comment]
I'm disappointed to see this won't be fixed.  I'll also note that the previous 4.5,x version of Invoice Ninja did _not_ display the version number on the login page, which was a smart move for security.  This was added in 5.x at some point and is such an easy thing to remove from the login page.

It's the same reason it's advised to not reveal the version of web server software you're running; an attacker can use this information to look for publicly disclosed vulnerabilities and by showing the version number to the public, you're revealing critical information about your infrastructure, which isn't good.
