### ISSUE TITLE
Add bulk download button to Reports

### ISSUE THREAD

**Issue by rephlex** [invoiceninja/ui#2177]
A bulk download button in the Reports tab could for example enable the user to quickly download all invoices written within a given month. This is particularly useful when working with external accountants / tax consultants.

I know it's possible to bulk download from within the "Invoices" tab already. This is OK for a handful of invoices, but in my case the invoices are spread over 3 pages and you have to check/unckeck quite a few boxes manually.

The flutter app already has this implemented quite nicely (see screenshot).
![Bildschirmfoto vom 2024-11-10 10-42-01](https://github.com/user-attachments/assets/d0673537-a18c-4ea6-8984-331fe4327a31)

**Comment by turbo124** [comment]
@rephlex we can add this as a feature request, just to note, you can filter the invoice list by date, so unless you have > 100 PDF's to download, the current UI should support what you are asking for.


![image](https://github.com/user-attachments/assets/5e675df8-4046-43f2-918d-c85ac330a866)

![image](https://github.com/user-attachments/assets/e66b87ee-2e1e-460b-b5a7-4b5f67713c5b)

**Comment by turbo124** [comment]
In the react application the option to also include PDFs in the report has been included now.

![image](https://github.com/user-attachments/assets/29c50a34-6375-42a6-8de6-8cf83b4aba36)

**Comment by turbo124** [comment]
In the react application the option to also include PDFs in the report has been included now.

![image](https://github.com/user-attachments/assets/29c50a34-6375-42a6-8de6-8cf83b4aba36)
