### ISSUE TITLE
[Self-hosted] “This action is unauthorized” Error in Invoice Ninja Docker Version 5.10.51

### ISSUE THREAD

**Issue by nascaline** [invoiceninja/ui#2197]
Subject: [Self-hosted] “This action is unauthorized” Error in Invoice Ninja Docker Version 5.10.51
Description: I am experiencing an issue with the self-hosted Invoice Ninja app in a Docker environment (version 5.10.51). The app prompts “This action is unauthorized.” I am unable to create any invoices or perform any actions with PDFs.
Steps To Reproduce:

1. Deploy Invoice Ninja in a Docker environment using version 5.10.51.
2. Attempt to create an invoice or perform any PDF-related actions.
3. Encounter the error message: “This action is unauthorized.”

![invoice ninjia unauthoried ](https://github.com/user-attachments/assets/3b6c4190-2019-442e-a30e-a106ed5a020f)

**Comment by turbo124** [comment]
i've tagged 5.10.52 with a fix, please reopen if you continue to see this.
