### ISSUE TITLE
Option to move "ACTIONS" buttons to the left

### ISSUE THREAD

**Issue by Connexiumlabs** [invoiceninja/ui#2234]
Invoice Ninja 5
Hosted
Web browser version

Please add an option to move the "ACTIONS" buttons to the left

![image](https://github.com/user-attachments/assets/08f72f34-d456-42b4-b819-528b52c96592)

**Additional context**
Action buttons are often hidden because of to many columns

**Comment by turbo124** [comment]
@beganovich is there a win to be found with customizing column width and storing in react_settings?

**Comment by beganovich** [comment]
I've experimented on this and got in-house demo working, so we will likely land this feature once we get enough time for it. 

Thanks for reaching out :+1:

**Comment by turbo124** [comment]
We'll close this and track here #2235

**Comment by Connexiumlabs** [comment]
Was the "Option to move "ACTIONS" buttons to the left" ever implemented? I dont see it in the Web client. Thank you

**Comment by turbo124** [comment]
@Connexiumlabs we chose to just provide the column resize option.

**Comment by Connexiumlabs** [comment]
Ok, i'll make another suggestion for this feature request with a little twist. Thanks for the resize option. Very useful for us.
