### ISSUE TITLE
Issue creating new api token on self hosted web app

### ISSUE THREAD

**Issue by Hypnocrit** [invoiceninja/ui#2236]
Interaction
Creating a token does not allow the user to see the token before it becomes hidden for security reasons.

Expected Result
When creating an API token, I should be able to copy the API token before it being hidden.

Actual result.
It redirects immediately to the edit token page and does not allow a chance to copy.  All I see is ****** for the token.

Environment:
Hosted on HTTP only, internal facing, not publicly facing instance.  Self hosted.
Apache2.
PHP8.2.  Shells running on same version of php.
No missing plugins and shells are running/nothing appearing in errors list on the bottom left.

Other details:
works on app.  So I am not blocked.

[Link to slack thread](https://invoiceninja.slack.com/archives/C9KSLL0TE/p1732786001672059)

**Comment by turbo124** [comment]
@Civolilah copy icon missing it seems
