### ISSUE TITLE
Two column filters for dates in tasks menu

### ISSUE THREAD

**Issue by bsian03** [invoiceninja/ui#2245]
In the tasks page, there's two options to filter by date. there should only be one. they seem to be identical in behaviour, but both can be used. screenshot is of both date filter columns added
![Screenshot_20241202-141201.png](https://github.com/user-attachments/assets/4ffc8ba0-7097-4286-8fb8-7b4c1bceae9a)

**Comment by turbo124** [comment]
I cannot recreate this. Do you have a custom field on your task record?

**Comment by bsian03** [comment]
sorry, yes I do and forgot. I'm assuming the date field there is for when the task starts?

**Comment by turbo124** [comment]
so Date is native column you have access to. along with any custom fields, in this case also another date field.
