### ISSUE TITLE
Missing custom field data from invoices

### ISSUE THREAD

**Issue by bsian03** [invoiceninja/ui#2246]
This may be a compatibility thing between flutter and react - however invoicing projects will not have a date set even when they're set in the individual tasks
![Screenshot_20241202-140425.png](https://github.com/user-attachments/assets/cbb66160-761f-4fd7-af85-012ac258eb55)

**Comment by turbo124** [comment]
these are custom fields on tasks that you want to have brough over to the invoice, right?

**Comment by turbo124** [comment]
@Civolilah please ensure that tasks custom fields are brought over to the invoice when converting to invoice.

**Comment by bsian03** [comment]
yes. this is sort of related to #2245. currently the behaviour on flutter is I have a date assigned as a custom field which doesn't happen here. will clarify title
