### ISSUE TITLE
Add Order Fulfilment Statuses

### ISSUE THREAD

**Issue by Waaiez** [invoiceninja/ui#2266]
First off, love the work you guys do, keep up the good work

**Feature request:**
We run a stationery and textbook business, and our invoice workflow involves multiple steps like packing and delivery. While the current financial status options (Draft, Sent, Viewed, Partial Payment, Paid, etc.) are perfect and should stay as they are, we need additional status column to track the fulfilment process.

**How it currently looks**
![image](https://github.com/user-attachments/assets/15cc1fe2-1e14-421f-afc4-570a15ad60e0)

**What I propose**
![image](https://github.com/user-attachments/assets/12bbabf3-9e22-4d2c-baca-46983128959c)

**Proposed New Statuses**
- Processing / Ready To Be Packed
- Packed
- Ready for Dispatch / Delivery
- Ready for Collection / Collection Scheduled
- Delivered
- Collected

**Why This is Needed**
Better Visibility: Helps different team members (invoicing, packing, delivery) see the current stage of each order at a glance.
Improved Coordination: Makes it easier to assign and track tasks across departments.
Streamlined Workflow: Reduces confusion and speeds up the order processing and delivery.

**Comment by turbo124** [comment]
Hi There,

You can use custom fields to manage this already.

Create a custom field in Invoices, and add your statuses, these can then be added to the table.

**Comment by Waaiez** [comment]
ah, that's brilliant
I didn't realise how powerful custom fields actually are
It works perfectly for our use case and can easily be set
Thank you 🙏

![image](https://github.com/user-attachments/assets/db4544a9-5cbb-465e-879f-e365d993c5fc)
![image](https://github.com/user-attachments/assets/57ff2cb7-d59b-4afe-a066-817980fa7d5f)
