### ISSUE TITLE
React Web App: Pressing enter doesn't drop to a new line

### ISSUE THREAD

**Issue by ryangravel** [invoiceninja/ui#2279]
Self Hosted 5.11.6

Creating or editing a line item/task description will not allow me to drop down a line by pressing enter.  I can recreate this with multiple machines and browsers.

react.invoicing.co has the same issue.

**Comment by turbo124** [comment]
https://github.com/user-attachments/assets/747c438e-80b1-4936-8c2a-1278036c078b

**Comment by turbo124** [comment]
tracking in #2281
