### ISSUE TITLE
Return not working in Textarea Fields anymore

### ISSUE THREAD

**Issue by simarilius** [invoiceninja/ui#2281]
## Setup
- Version: v5.11.6
- Environment: Shared Hosting

## Interface
- Flutter: []
- React: [x]
- Both: []

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo? 
Yes on react.imvoiceninja.co
- Have you searched existing issues? Yes
- Have you reported this to Slack/forum before posting? No
- Have you inspected the logs in storage/logs/laravel.log for any errors?  Yes

## Describe the bug
Since the update (Friday) i can't press return or cursor Up / down in normal Textarea fields. In WYSWYG Fields it works

### Steps To Reproduce
e.g.:
Invoices -> Edit Invoice
Try to edit Description of an Produkt
or at the custom invoice design...

### Expected Behavior
I can press return to add a new line
Can move the cursor with up / down Buttons

## Additional context
Tested with Mac and Windows and on the react demo site

**Comment by turbo124** [comment]
@beganovich @Civolilah 

I can recreate this.

**Comment by beganovich** [comment]
Fixed in #2282.
