### ISSUE TITLE
Invoice of task showing 0,00 hours in the overview

### ISSUE THREAD

**Issue by glennbossitbe** [invoiceninja/ui#2284]
When creating an invoice from a task the hour counter is not working.
![image](https://github.com/user-attachments/assets/ac33c263-74d9-4736-8bff-83e24d1eb9db)
![image](https://github.com/user-attachments/assets/96fb870a-f4c6-4ae2-8573-a21c1d1b02d3)

The counter is working when you invoice the project as a whole, but my project is running multiple months and expecting monthly invoicing.

**Comment by turbo124** [comment]
What version are you on? this issue has been corrected in 5.11.7

**Comment by glennbossitbe** [comment]
Indeed, it is fixed after the update.
    Thank you.
    
    On 30/12/2024 23:21, David Bomba wrote:
    
    
      
      What version are you on? this issue has been
        corrected in 5.11.7
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/invoiceninja/ui/issues/2284#issuecomment-2565967206",
"url": "https://github.com/invoiceninja/ui/issues/2284#issuecomment-2565967206",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
