### ISSUE TITLE
Company documents messed up

### ISSUE THREAD

**Issue by hismayilov** [invoiceninja/ui#288]
For multiple companies, it shows unrelated documents.

![image](https://user-images.githubusercontent.com/676555/204161869-9766765f-43ea-446a-b2a8-e8a6aed14e94.png)

**Comment by turbo124** [comment]
This is a bug, we are checking in a fix for this, both in the UI and also the API, so the next release will have this issue patched.

**Comment by beganovich** [comment]
Fixed in #289. Thanks for reporting it!
