### ISSUE TITLE
Missing translation and currency

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/ui#367]
Hi everybody,
just switched to the nee frontend:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/28981528/211519220-74315299-c599-4fe1-9033-069d3cf6dd4f.png">
I noticed, that the Company currency isn't applied, and in the payment graph the dates aren't translated.

**Comment by LarsK1** [comment]
Addition: all dates aren't localised

**Comment by beganovich** [comment]
Hi,
Thanks for catching this. 

What is the company's country? Germany?

**Comment by LarsK1** [comment]
Hi,
shure. Yes, it's germany.
