### ISSUE TITLE
Add/Remove columns to entity pages 

### ISSUE THREAD

**Issue by hismayilov** [invoiceninja/ui#388]
in Admin Portal
![image](https://user-images.githubusercontent.com/676555/212557436-8ac94af5-0870-4607-8437-f8a56d1ce534.png)
in React App, it is not possible to add custom fields as a column.
![image](https://user-images.githubusercontent.com/676555/212557492-9a417bfa-5ea8-4285-b353-cc10cefb72af.png)

**Comment by turbo124** [comment]
@hismayilov 

thanks for reporting, we've added to backlog, ping @Civolilah

**Comment by turbo124** [comment]
@hismayilov We are unable to recreate this, are you adding a label for the custom field?

**Comment by hismayilov** [comment]
> 

I am using custom fields in the invoice header level, and in the invoices list, I want to add those columns to the report/list. 
![image](https://user-images.githubusercontent.com/676555/221380495-83e38972-3f55-47e4-a8cd-38fb53b75219.png)
 hmmm I have selected wrong issue description :)

**Comment by turbo124** [comment]
@hismayilov this looks like the flutter app, should this be in the react repo? or in the flutter one?

**Comment by turbo124** [comment]
@hismayilov this looks like the flutter app, should this be in the react repo? or in the flutter one?

**Comment by hismayilov** [comment]
> @hismayilov this looks like the flutter app, should this be in the react repo? or in the flutter one?

The screen is from flutter app, but I want to do the same customizing(display/hide columns) in React app too.

**Comment by beganovich** [comment]
Does this help?

![image](https://user-images.githubusercontent.com/13711415/221550997-3d0e5561-6fcc-493e-a73c-183f79f31ed8.png)

**Comment by hismayilov** [comment]
> Does this help?
> 
> ![image](https://user-images.githubusercontent.com/13711415/221550997-3d0e5561-6fcc-493e-a73c-183f79f31ed8.png)

Absolutely :)

**Comment by hismayilov** [comment]
> Does this help?
> 
> ![image](https://user-images.githubusercontent.com/13711415/221550997-3d0e5561-6fcc-493e-a73c-183f79f31ed8.png)

But I don see my custom fields in drop down list
![image](https://user-images.githubusercontent.com/676555/225552080-2f8c4a7e-8692-4bc7-99c0-cdc704bea992.png)

**Comment by beganovich** [comment]
Ah, looks like we haven't implemented names for them yet. But they're there. "First custom, second..".
