### ISSUE TITLE
Invoice preview is not being updated properly.

### ISSUE THREAD

**Issue by hismayilov** [invoiceninja/ui#389]
Open Invoice from Client A
![image](https://user-images.githubusercontent.com/676555/212557991-5decbbd2-a2be-4923-932e-7d3beb0b2b48.png)

go to invoice list, open invoice from client B.
Check preview details.
![image](https://user-images.githubusercontent.com/676555/212558007-bf13b5d6-5a75-4206-8f77-a912df17368d.png)

in both invoices client is Client A. 
running on docker-compose, - PDF is generated by SnapPDF, Self-hosted.

**Comment by turbo124** [comment]
@hismayilov 

Thanks for reporting, i see the issue here, the pdf preview is cached from the previous invoice, when an edit is made to the invoice, the pdf does update correctly, so just looks like a cache issues.

added to backlog

ping @Civolilah

**Comment by turbo124** [comment]
#498
