### ISSUE TITLE
Purchase Orders not shown in Vendor Page

### ISSUE THREAD

**Issue by hismayilov** [invoiceninja/ui#391]
in Vendor Page., purchase orders not listed. 
Vendor Page
![image](https://user-images.githubusercontent.com/676555/212559995-66e81d88-6468-4721-bb5c-02ab9e0fa7b3.png)

But there is a purchase order exists for it. 
![image](https://user-images.githubusercontent.com/676555/212559791-cdbf0d84-371b-4bfb-a873-89dd33301cfd.png)

**Comment by turbo124** [comment]
Thanks we have this in backlog 

ping @Civolilah RU-499
