### ISSUE TITLE
Subject of sendEmail not editable

### ISSUE THREAD

**Issue by paulwer** [invoiceninja/ui#515]
I just noticed a difference between the flutter app and the react app. within flutter, i was able to edit the subject, when sending a email to a invoice. within react this was not possible.

I guess the react app probably does not reconise my white-label-license, because i get the buy option on the dashboard too.

**Comment by turbo124** [comment]
@paulwer 

Can you share a screen shot of the field as blocked from editting? we don't restrict the email subject regardless of whitelabel or not.

I am also unable to replicate on my setup.

**Comment by paulwer** [comment]
when i take a look at the code of the ui, there is a checkup, which looks like it would be restricted:

<InputField
            label={t('subject')}
            value={subject || template?.raw_subject}
            onValueChange={(value) => setSubject(value)}
            **disabled={freePlan()}**
          />

in https://github.com/invoiceninja/ui/blob/main/src/pages/invoices/email/components/Mailer.tsx

![Unbenannt](https://user-images.githubusercontent.com/52678724/222722885-fefe32da-69ca-41af-805d-1b24ae639220.png)

**Comment by turbo124** [comment]
@Civolilah can you see if there is any explanation for this for self hosted users please?

**Comment by Civolilah** [comment]
> 

@turbo124 Of course, I will take a look into this as soon as possible and get back.
