### ISSUE TITLE
Dashboard open invoices shows payed invoices

### ISSUE THREAD

**Issue by LaurensVanAcker** [invoiceninja/ui#566]
The invoices part in the dashboard shows invoices which are paid with a remaining balance of 0.

**Comment by turbo124** [comment]
@LaurensVanAcker 

can you share a screenshot please?

**Comment by LaurensVanAcker** [comment]
Yes, sure. The table shows all invoices that have yet to expire, regardless of whether they are paid. In v4, you only saw the unpaid.

![Screenshot 2023-03-26 133940](https://user-images.githubusercontent.com/4385000/227773352-a2e616d0-026a-45de-b91f-5ada4c787bc8.png)
![Screenshot 2023-03-26 134152](https://user-images.githubusercontent.com/4385000/227773353-48a6f394-0e80-4641-9502-be7cc3cc0c74.png)

**Comment by turbo124** [comment]
Thanks for reporting this, fix is here

#8406

Avaiilable in the next release
