### ISSUE TITLE
Settings - modules: missing Transactions

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/ui#710]
Hi,
in the module section "Transactions" is missing. Even when the module is disabled using the old app. It's shown in the sidebar.
<img width="354" alt="image" src="https://github.com/invoiceninja/ui/assets/28981528/3e941f47-cb24-4e28-84dd-2599446661d7">

**Comment by turbo124** [comment]
Are you on the latest release? this has been checked in recently

**Comment by LarsK1** [comment]
Hi,
I'm running v5.5.124?

**Comment by LarsK1** [comment]
Will report back, once updated 👍

**Comment by LarsK1** [comment]
@turbo124 after the update it works, just as promised 👍

**Comment by beganovich** [comment]
Thanks for confirmation!
