### ISSUE TITLE
Settings - client portal

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/ui#712]
Hi,
in the settings all client portal values are not set. On the main page the setting for the po-number and for an external store is missing.
<img width="318" alt="image" src="https://github.com/invoiceninja/ui/assets/28981528/45e4a353-3e37-4f1c-9c49-34bb4da4bce9">

The registration tab provides also wrong data:
old
<img width="413" alt="image" src="https://github.com/invoiceninja/ui/assets/28981528/1574dbee-cc05-4ba8-97b9-cc2af1598ae2">
new
<img width="474" alt="image" src="https://github.com/invoiceninja/ui/assets/28981528/60f33af7-4069-4c21-a65b-285ef997caa0">

**Comment by turbo124** [comment]
#717
