### ISSUE TITLE
Wrong amount format in balance and paid to date columns in Clients

### ISSUE THREAD

**Issue by alexgauvin** [invoiceninja/ui#829]
Wrong amount format in balance and paid to date columns in Clients.
Some with currency symbol, other without.
![Screenshot_5](https://github.com/invoiceninja/ui/assets/5897903/d170057f-4322-40f7-8233-d3b45b5b99bc)

**Comment by turbo124** [comment]
I'm see this elsewhere also. @Civolilah can you please add this to backlog for investigation.

**Comment by turbo124** [comment]
@alexgauvin I believe this is now resolved, can we close this if you are not seeing this issue anymore?

**Comment by alexgauvin** [comment]
@turbo124 Yes, the format is now correct. But I think amounts should be right aligned

**Comment by turbo124** [comment]
ok closing the primary issue raised on this one. I'm not sure there is anything we can do with alignments as yet.
