### ISSUE TITLE
Dashboard - rounding and currency sign

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/ui#885]
Hi,
since the latest update the graphs are now localised. Thank you!!!
But the y-scale misses a currency sign, and the data points are not rounded and miss a currency sign as well:
![image](https://github.com/invoiceninja/ui/assets/28981528/7cfc3f9b-41a1-4bbb-bb5d-50bd27930ee4)

**Comment by turbo124** [comment]
@LarsK1 

We've checked in a fix for the currency sign which is pending merge.

**Comment by LarsK1** [comment]
Hi @turbo124,
thanks for letting me know, but PR #873 only includes a bugfix for the tool-tip, but not for the y-axis.

**Comment by turbo124** [comment]
@LarsK1 

Thanks i'll get that added to backlog.
