### ISSUE TITLE
Dashboard widgets do not refresh

### ISSUE THREAD

**Issue by alexgauvin** [invoiceninja/ui#949]
Hi,

In React, on my Selfhost install, widgets are not refreshing as they should after some actions.

As an example, Past Due Invoices has not refreshed after entering a payment for a few invoices listed in this widget.

Browsing to another page and coming back to Dashboard did not help
Only after a hard refresh did theses now paid invoices were removed from this widget list.

IMO, it should not need a hard refresh to update these widget infos.

**Comment by turbo124** [comment]
This should be resolved in the next release.
